# Generated by Django 5.1.5 on 2025-04-04 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaEmissionRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('banoxrta', models.FloatField(blank=True, null=True)),
                ('banoxrto', models.FloatField(blank=True, null=True)),
                ('baso2rta', models.FloatField(blank=True, null=True)),
                ('baco2rta', models.FloatField(blank=True, null=True)),
                ('bach4rta', models.FloatField(blank=True, null=True)),
                ('ban2orta', models.FloatField(blank=True, null=True)),
                ('bac2erta', models.FloatField(blank=True, null=True)),
                ('bahgrta', models.CharField(blank=True, null=True)),
                ('banoxra', models.FloatField(blank=True, null=True)),
                ('banoxro', models.FloatField(blank=True, null=True)),
                ('baso2ra', models.FloatField(blank=True, null=True)),
                ('baco2ra', models.FloatField(blank=True, null=True)),
                ('bach4ra', models.FloatField(blank=True, null=True)),
                ('ban2ora', models.FloatField(blank=True, null=True)),
                ('bac2era', models.FloatField(blank=True, null=True)),
                ('bahgra', models.CharField(blank=True, null=True)),
                ('banoxcrt', models.FloatField(blank=True, null=True)),
                ('banoxcro', models.FloatField(blank=True, null=True)),
                ('baso2crt', models.FloatField(blank=True, null=True)),
                ('baco2crt', models.FloatField(blank=True, null=True)),
                ('bach4crt', models.FloatField(blank=True, null=True)),
                ('ban2ocrt', models.FloatField(blank=True, null=True)),
                ('bac2ecrt', models.FloatField(blank=True, null=True)),
                ('bahgcrt', models.CharField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('bacode', models.ForeignKey(db_column='bacode', on_delete=django.db.models.deletion.CASCADE, to='egrid.balancingauthority')),
            ],
            options={
                'db_table': 'ba_emission_rate',
            },
        ),
    ]
