# Generated by Django 5.1.5 on 2025-04-08 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0008_alter_nercadjustedvalues_nerc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statefueltypeemissionrate',
            name='fipsst',
            field=models.ForeignKey(db_column='fipsst', on_delete=django.db.models.deletion.CASCADE, to='egrid.state', to_field='fipsst'),
        ),
        migrations.AlterField(
            model_name='statenonbaseloadvalues',
            name='fipsst',
            field=models.ForeignKey(db_column='fipsst', on_delete=django.db.models.deletion.CASCADE, to='egrid.state', to_field='fipsst'),
        ),
        migrations.AlterField(
            model_name='stateresourcemix',
            name='fipsst',
            field=models.ForeignKey(db_column='fipsst', on_delete=django.db.models.deletion.CASCADE, to='egrid.state', to_field='fipsst'),
        ),
    ]
