# Generated by Django 5.1.5 on 2025-04-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0010_alter_stateadjustedvalues_fipsst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitunadjustedvalues',
            name='so2ctldv',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
