# Generated by Django 5.1.5 on 2025-04-14 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0012_remove_unitunadjustedvalues_so2ctldc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantadjustedvalues',
            name='orispl',
            field=models.ForeignKey(db_column='orispl', on_delete=django.db.models.deletion.CASCADE, to='egrid.plant', to_field='orispl'),
        ),
        migrations.AlterField(
            model_name='plantemissionrate',
            name='orispl',
            field=models.ForeignKey(db_column='orispl', on_delete=django.db.models.deletion.CASCADE, to='egrid.plant', to_field='orispl'),
        ),
        migrations.AlterField(
            model_name='plantfueltypegeneration',
            name='orispl',
            field=models.ForeignKey(db_column='orispl', on_delete=django.db.models.deletion.CASCADE, to='egrid.plant', to_field='orispl'),
        ),
        migrations.AlterField(
            model_name='plantresourcemix',
            name='orispl',
            field=models.ForeignKey(db_column='orispl', on_delete=django.db.models.deletion.CASCADE, to='egrid.plant', to_field='orispl'),
        ),
        migrations.AlterField(
            model_name='plantunadjustedvalues',
            name='orispl',
            field=models.ForeignKey(db_column='orispl', on_delete=django.db.models.deletion.CASCADE, to='egrid.plant', to_field='orispl'),
        ),
    ]
