# Generated by Django 5.1.5 on 2025-04-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0017_alter_plant_bacode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='baadjustedvalues',
            constraint=models.UniqueConstraint(fields=('bacode', 'year'), name='bav_unique_bacode_year'),
        ),
    ]
