# Generated by Django 5.1.5 on 2025-04-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0018_baadjustedvalues_bav_unique_bacode_year'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='baemissionrate',
            constraint=models.UniqueConstraint(fields=('bacode', 'year'), name='ber_unique_bacode_year'),
        ),
        migrations.AddConstraint(
            model_name='bafueltypeemissionrate',
            constraint=models.UniqueConstraint(fields=('bacode', 'year'), name='ba_fuel_type_emission_rate_unique_bacode_year'),
        ),
    ]
