# Generated by Django 5.2 on 2025-04-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0022_plantunadjustedvalues_unco2src"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="plantadjustedvalues",
            name="plant_adjusted_values_unique_bacode_year",
        ),
        migrations.RemoveConstraint(
            model_name="plantemissionrate",
            name="plant_emission_rate_unique_bacode_year",
        ),
        migrations.RemoveConstraint(
            model_name="plantfueltypegeneration",
            name="plant_fuel_type_gen_unique_bacode_year",
        ),
        migrations.RemoveConstraint(
            model_name="plantresourcemix",
            name="plant_resource_mix_unique_bacode_year",
        ),
        migrations.RemoveConstraint(
            model_name="plantunadjustedvalues",
            name="plant_unadjusted_values_unique_bacode_year",
        ),
        migrations.AddConstraint(
            model_name="nercadjustedvalues",
            constraint=models.UniqueConstraint(
                fields=("nerc", "year"), name="nerc_adjusted_values_unique_nerc_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="nercemissionrate",
            constraint=models.UniqueConstraint(
                fields=("nerc", "year"), name="nerc_emission_rate_unique_nerc_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="nercfueltypeemissionrate",
            constraint=models.UniqueConstraint(
                fields=("nerc", "year"),
                name="nerc_fuel_type_emission_rate_unique_nerc_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="nercfueltypegeneration",
            constraint=models.UniqueConstraint(
                fields=("nerc", "year"),
                name="nerc_fuel_type_generation_unique_nerc_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="nercnonbaseloadvalues",
            constraint=models.UniqueConstraint(
                fields=("nerc", "year"), name="nerc_nonbaseload_values_unique_nerc_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="nercresourcemix",
            constraint=models.UniqueConstraint(
                fields=("nerc", "year"), name="nerc_resource_mix_unique_nerc_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="plantadjustedvalues",
            constraint=models.UniqueConstraint(
                fields=("orispl", "year"),
                name="plant_adjusted_values_unique_orispl_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="plantemissionrate",
            constraint=models.UniqueConstraint(
                fields=("orispl", "year"), name="plant_emission_rate_unique_orispl_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="plantfueltypegeneration",
            constraint=models.UniqueConstraint(
                fields=("orispl", "year"), name="plant_fuel_type_gen_unique_orispl_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="plantresourcemix",
            constraint=models.UniqueConstraint(
                fields=("orispl", "year"), name="plant_resource_mix_unique_orispl_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="plantunadjustedvalues",
            constraint=models.UniqueConstraint(
                fields=("orispl", "year"),
                name="plant_unadjusted_values_unique_orispl_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="stateadjustedvalues",
            constraint=models.UniqueConstraint(
                fields=("fipsst", "year"),
                name="state_adjusted_values_unique_fipsst_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="stateemissionrate",
            constraint=models.UniqueConstraint(
                fields=("fipsst", "year"), name="state_emission_rate_unique_fipsst_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="statefueltypeemissionrate",
            constraint=models.UniqueConstraint(
                fields=("fipsst", "year"),
                name="state_fuel_type_emission_rate_unique_fipsst_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="statefueltypegeneration",
            constraint=models.UniqueConstraint(
                fields=("fipsst", "year"),
                name="state_fuel_type_generation_unique_fipsst_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="statenonbaseloadvalues",
            constraint=models.UniqueConstraint(
                fields=("fipsst", "year"),
                name="state_nonbaseload_values_unique_fipsst_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="stateresourcemix",
            constraint=models.UniqueConstraint(
                fields=("fipsst", "year"), name="state_resource_mix_unique_fipsst_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="subrgnadjustedvalues",
            constraint=models.UniqueConstraint(
                fields=("subrgn", "year"),
                name="subregion_adjusted_values_unique_subrgn_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="subrgnemissionrate",
            constraint=models.UniqueConstraint(
                fields=("subrgn", "year"),
                name="subregion_emission_rate_unique_subrgn_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="subrgnfueltypeemissionrate",
            constraint=models.UniqueConstraint(
                fields=("subrgn", "year"),
                name="subregion_fuel_type_emission_rate_unique_subrgn_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="subrgnfueltypegeneration",
            constraint=models.UniqueConstraint(
                fields=("subrgn", "year"),
                name="subregion_fuel_type_generation_unique_subrgn_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="subrgnnonbaseloadvalues",
            constraint=models.UniqueConstraint(
                fields=("subrgn", "year"),
                name="subregion_nonbaseload_values_unique_subrgn_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="subrgnresourcemix",
            constraint=models.UniqueConstraint(
                fields=("subrgn", "year"),
                name="subregion_resource_mix_unique_subrgn_year",
            ),
        ),
    ]
