# Generated by Django 5.2 on 2025-04-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "egrid",
            "0023_remove_plantadjustedvalues_plant_adjusted_values_unique_bacode_year_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="baemissionrate",
            name="ber_unique_bacode_year",
        ),
        migrations.AddConstraint(
            model_name="baemissionrate",
            constraint=models.UniqueConstraint(
                fields=("bacode", "year"), name="ba_emission_rate_unique_bacode_year"
            ),
        ),
    ]
