# Generated by Django 5.1.5 on 2025-07-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0025_plant_capfac'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantadjustedvalues',
            name='capfac',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
