# Generated by Django 5.1.5 on 2025-07-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0026_plantadjustedvalues_capfac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='capfac',
        ),
    ]
