# Generated by Django 5.1.5 on 2025-07-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0027_remove_plant_capfac'),
    ]

    operations = [
        migrations.DeleteModel(
            name='County',
        ),
    ]
