# Generated by Django 5.2 on 2025-08-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0030_alter_plant_fipscnty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utility',
            new_name='PlantUtility',
        ),
        migrations.RemoveField(
            model_name='plantdistributionsys',
            name='orispl',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.RemoveField(
            model_name='balancingauthority',
            name='banamepcap',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='seqgen',
        ),
        migrations.RemoveField(
            model_name='nercregion',
            name='nrnamepcap',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='namepcap',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='seqplt',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='utlsrvid',
        ),
        migrations.RemoveField(
            model_name='state',
            name='stnamepcap',
        ),
        migrations.RemoveField(
            model_name='subregion',
            name='srnamepcap',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='sequnt',
        ),
        migrations.AddField(
            model_name='plant',
            name='oprname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='subrgnadjustedvalues',
            name='srnamepcap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baadjustedvalues',
            name='bahtian',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bafueltypeemissionrate',
            name='bachgr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bafueltypeemissionrate',
            name='bachgrt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bafueltypeemissionrate',
            name='bafshgr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bafueltypeemissionrate',
            name='bafshgrt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banonbaseloadvalues',
            name='banbhg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='subrgn',
            field=models.CharField(default=99, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subrgnnonbaseloadvalues',
            name='srnbhg',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='plantutility',
            table='plant_utility',
        ),
        migrations.DeleteModel(
            name='PlantDistributionSys',
        ),
    ]
