# Generated by Django 5.2 on 2025-08-07 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0031_rename_utility_plantutility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='utlsrvid',
            field=models.ForeignKey(db_column='utlsrvid', default=99, on_delete=django.db.models.deletion.CASCADE, to='egrid.plantutility'),
            preserve_default=False,
        ),
    ]
