# Generated by Django 5.2 on 2025-08-07 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0032_plant_utlsrvid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='subrgn',
            field=models.ForeignKey(db_column='subrgn', on_delete=django.db.models.deletion.CASCADE, to='egrid.subregion'),
        ),
    ]
