-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2025-01-22 15:25:21 EST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE
-- added 
CREATE TABLE ba_annual_combustion (
    id         NUMBER NOT NULL,
    ba_id      NUMBER NOT NULL,
    bahtian    NUMBER,
    bahtioz    NUMBER,
    bahtiant   NUMBER,
    bahtiozt   NUMBER,
    bangenan   NUMBER,
    bangenoz   NUMBER,
    banoxan    NUMBER,
    banoxoz    NUMBER,
    baso2an    NUMBER,
    baco2an    NUMBER,
    bach4an    NUMBER,
    ban2oan    NUMBER,
    baco2eqa   NUMBER,
    bahgan     NUMBER,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

COMMENT ON COLUMN ba_annual_combustion.bahtian IS
    'BA annual heat input from combustion (MMBtu)
';

COMMENT ON COLUMN ba_annual_combustion.bahtioz IS
    'BA ozone season heat input from combustion (MMBtu)
';

COMMENT ON COLUMN ba_annual_combustion.bahtiant IS
    'BA total annual heat input (MMBtu)
';

COMMENT ON COLUMN ba_annual_combustion.bahtiozt IS
    'BA total ozone season heat input (MMBtu)
';

COMMENT ON COLUMN ba_annual_combustion.bangenan IS
    'BA annual net generation (MWh)
';

COMMENT ON COLUMN ba_annual_combustion.bangenoz IS
    'BA ozone season net generation (MWh)
';

COMMENT ON COLUMN ba_annual_combustion.banoxan IS
    'BA annual NOx emissions (tons)
';

COMMENT ON COLUMN ba_annual_combustion.banoxoz IS
    'BA ozone season NOx emissions (tons)
';

COMMENT ON COLUMN ba_annual_combustion.baso2an IS
    'BA annual SO2 emissions (tons)
';

COMMENT ON COLUMN ba_annual_combustion.baco2an IS
    'BA annual CO2 emissions (tons)
';

COMMENT ON COLUMN ba_annual_combustion.bach4an IS
    'BA annual CH4 emissions (lbs)
';

COMMENT ON COLUMN ba_annual_combustion.ban2oan IS
    'BA annual N2O emissions (lbs)
';

COMMENT ON COLUMN ba_annual_combustion.baco2eqa IS
    'BA annual CO2 equivalent emissions (tons)
';

COMMENT ON COLUMN ba_annual_combustion.bahgan IS
    'BA annual Hg emissions (lbs)
';

ALTER TABLE ba_annual_combustion ADD CONSTRAINT ba_annual_combustion_pk PRIMARY KEY ( id );

CREATE TABLE ba_emission_rate (
    id         NUMBER NOT NULL,
    ba_id      NUMBER NOT NULL,
    banoxrta   NUMBER,
    banoxrto   NUMBER,
    baso2rta   NUMBER,
    baco2rta   NUMBER,
    bach4rta   NUMBER,
    ban2orta   NUMBER,
    bac2erta   NUMBER,
    bahgrta    NUMBER,
    banoxra    NUMBER,
    banoxro    NUMBER,
    baso2ra    NUMBER,
    baco2ra    NUMBER,
    bach4ra    NUMBER,
    ban2ora    NUMBER,
    bac2era    NUMBER,
    bahgra     NUMBER,
    banoxcrt   NUMBER,
    banoxcro   NUMBER,
    baso2crt   NUMBER,
    baco2crt   NUMBER,
    bach4crt   NUMBER,
    ban2ocrt   NUMBER,
    bac2ecrt   NUMBER,
    bahgcrt    NUMBER,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

COMMENT ON COLUMN ba_emission_rate.banoxrta IS
    'BA annual NOx total output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_emission_rate.banoxrto IS
    'BA ozone season NOx total output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_emission_rate.baso2rta IS
    'BA annual SO2 total output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_emission_rate.baco2rta IS
    'BA annual CO2 total output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_emission_rate.bach4rta IS
    'BA annual CH4 total output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_emission_rate.ban2orta IS
    'BA annual N2O total output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_emission_rate.bac2erta IS
    'BA annual CO2 equivalent total output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_emission_rate.bahgrta IS
    'BA annual Hg total output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_emission_rate.banoxra IS
    'BA annual NOx input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_emission_rate.banoxro IS
    'BA ozone season NOx input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_emission_rate.baso2ra IS
    'BA annual SO2 input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_emission_rate.baco2ra IS
    'BA annual CO2 input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_emission_rate.bach4ra IS
    'BA annual CH4 input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_emission_rate.ban2ora IS
    'BA annual N2O input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_emission_rate.bac2era IS
    'BA annual CO2 equivalent input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_emission_rate.bahgra IS
    'BA annual Hg input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_emission_rate.banoxcrt IS
    'BA annual NOx combustion output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_emission_rate.banoxcro IS
    'BA ozone season NOx combustion output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_emission_rate.baso2crt IS
    'BA annual SO2 combustion output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_emission_rate.baco2crt IS
    'BA annual CO2 combustion output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_emission_rate.bach4crt IS
    'BA annual CH4 combustion output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_emission_rate.ban2ocrt IS
    'BA annual N2O combustion output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_emission_rate.bac2ecrt IS
    'BA annual CO2 equivalent combustion output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_emission_rate.bahgcrt IS
    'BA annual Hg combustion output emission rate (lb/MWh)
';

ALTER TABLE ba_emission_rate ADD CONSTRAINT ba_emission_rate_pk PRIMARY KEY ( id );

-- added
CREATE TABLE ba_fuel_type_emission_rate (
    id         NUMBER NOT NULL,
    ba_id      NUMBER NOT NULL,
    bacnoxrt   NUMBER,
    baonoxrt   NUMBER,
    bagnoxrt   NUMBER,
    bafsnxrt   NUMBER,
    bacnxort   NUMBER,
    baonxort   NUMBER,
    bagnxort   NUMBER,
    bafsnort   NUMBER,
    bacso2rt   NUMBER,
    baoso2rt   NUMBER,
    bagso2rt   NUMBER,
    bafss2rt   NUMBER,
    bacco2rt   NUMBER,
    baoco2rt   NUMBER,
    bagco2rt   NUMBER,
    bafsc2rt   NUMBER,
    bacch4rt   NUMBER,
    baoch4rt   NUMBER,
    bagch4rt   NUMBER,
    bafch4rt   NUMBER,
    bacn2ort   NUMBER,
    baon2ort   NUMBER,
    bagn2ort   NUMBER,
    bafn2ort   NUMBER,
    bacc2ert   NUMBER,
    baoc2ert   NUMBER,
    bagc2ert   NUMBER,
    bafsc2ert  NUMBER,
    bachgrt    NUMBER,
    bafshgrt   NUMBER,
    bacnoxr    NUMBER,
    baonoxr    NUMBER,
    bagnoxr    NUMBER,
    bafsnxr    NUMBER,
    bacnxor    NUMBER,
    baonxor    NUMBER,
    bagnxor    NUMBER,
    bafsnor    NUMBER,
    bacso2r    NUMBER,
    baoso2r    NUMBER,
    bagso2r    NUMBER,
    bafss2r    NUMBER,
    bacco2r    NUMBER,
    baoco2r    NUMBER,
    bagco2r    NUMBER,
    bafsc2r    NUMBER,
    bacch4r    NUMBER,
    baoch4r    NUMBER,
    bagch4r    NUMBER,
    bafch4r    NUMBER,
    bacn2or    NUMBER,
    baon2or    NUMBER,
    bagn2or    NUMBER,
    bafn2or    NUMBER,
    bacc2er    NUMBER,
    baoc2er    NUMBER,
    bagc2er    NUMBER,
    bafsc2er   NUMBER,
    bachgr     NUMBER,
    bafshgr    NUMBER,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

COMMENT ON COLUMN ba_fuel_type_emission_rate.bacnoxrt IS
    'BA annual NOx coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.baonoxrt IS
    'BA annual NOx oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bagnoxrt IS
    'BA annual NOx gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bafsnxrt IS
    'BA annual NOx fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bacnxort IS
    'BA ozone season NOx coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.baonxort IS
    'BA ozone season NOx oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bagnxort IS
    'BA ozone season NOx gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bafsnort IS
    'BA ozone season NOx fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bacso2rt IS
    'BA annual SO2 coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.baoso2rt IS
    'BA annual SO2 oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bagso2rt IS
    'BA annual SO2 gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bafss2rt IS
    'BA annual SO2 fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bacco2rt IS
    'BA annual CO2 coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.baoco2rt IS
    'BA annual CO2 oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bagco2rt IS
    'BA annual CO2 gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bafsc2rt IS
    'BA annual CO2 fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bacch4rt IS
    'BA annual CH4 coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.baoch4rt IS
    'BA annual CH4 oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bagch4rt IS
    'BA annual CH4 gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bafch4rt IS
    'BA annual CH4 fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bacn2ort IS
    'BA annual N2O coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.baon2ort IS
    'BA annual N2O oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bagn2ort IS
    'BA annual N2O gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bafn2ort IS
    'BA annual N2O fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bacc2ert IS
    'BA annual CO2 equivalent coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.baoc2ert IS
    'BA annual CO2 equivalent oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bagc2ert IS
    'BA annual CO2 equivalent gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bafsc2ert IS
    'BA annual CO2 equivalent fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bachgrt IS
    'BA annual Hg coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bafshgrt IS
    'BA annual Hg fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bacnoxr IS
    'BA annual NOx coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.baonoxr IS
    'BA annual NOx oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bagnoxr IS
    'BA annual NOx gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bafsnxr IS
    'BA annual NOx fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bacnxor IS
    'BA ozone season NOx coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.baonxor IS
    'BA ozone season NOx oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bagnxor IS
    'BA ozone season NOx gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bafsnor IS
    'BA ozone season NOx fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bacso2r IS
    'BA annual SO2 coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.baoso2r IS
    'BA annual SO2 oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bagso2r IS
    'BA annual SO2 gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bafss2r IS
    'BA annual SO2 fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bacco2r IS
    'BA annual CO2 coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.baoco2r IS
    'BA annual CO2 oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bagco2r IS
    'BA annual CO2 gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bafsc2r IS
    'BA annual CO2 fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bacch4r IS
    'BA annual CH4 coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.baoch4r IS
    'BA annual CH4 oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bagch4r IS
    'BA annual CH4 gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bafch4r IS
    'BA annual CH4 fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bacn2or IS
    'BA annual N2O coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.baon2or IS
    'BA annual N2O oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bagn2or IS
    'BA annual N2O gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bafn2or IS
    'BA annual N2O fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bacc2er IS
    'BA annual CO2 equivalent coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.baoc2er IS
    'BA annual CO2 equivalent oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bagc2er IS
    'BA annual CO2 equivalent gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bafsc2er IS
    'BA annual CO2 equivalent fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bachgr IS
    'BA annual Hg coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN ba_fuel_type_emission_rate.bafshgr IS
    'BA annual Hg fossil fuel input emission rate (lb/MMBtu)
';

ALTER TABLE ba_fuel_type_emission_rate ADD CONSTRAINT ba_fuel_type_emission_rate_pk PRIMARY KEY ( id );

-- added
-- path this is ....
CREATE TABLE ba_fuel_type_generation (
    id         NUMBER NOT NULL,
    ba_id      NUMBER NOT NULL,
    bagenacl   NUMBER,
    bagenaol   NUMBER,
    bagenags   NUMBER,
    bagenanc   NUMBER,
    bagenahy   NUMBER,
    bagenabm   NUMBER,
    bagenawi   NUMBER,
    bagenaso   NUMBER,
    bagenagt   NUMBER,
    bagenaof   NUMBER,
    bagenaop   NUMBER,
    bagenatn   NUMBER,
    bagenatr   NUMBER,
    bagenath   NUMBER,
    bagenacy   NUMBER,
    bagenacn   NUMBER,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

COMMENT ON COLUMN ba_fuel_type_generation.bagenacl IS
    'BA annual coal net generation (MWh)
';

COMMENT ON COLUMN ba_fuel_type_generation.bagenaol IS
    'BA annual oil net generation (MWh)
';

COMMENT ON COLUMN ba_fuel_type_generation.bagenags IS
    'BA annual gas net generation (MWh)
';

COMMENT ON COLUMN ba_fuel_type_generation.bagenanc IS
    'BA annual nuclear net generation (MWh)
';

COMMENT ON COLUMN ba_fuel_type_generation.bagenahy IS
    'BA annual hydro net generation (MWh)
';

COMMENT ON COLUMN ba_fuel_type_generation.bagenabm IS
    'BA annual biomass net generation (MWh)
';

COMMENT ON COLUMN ba_fuel_type_generation.bagenawi IS
    'BA annual wind net generation (MWh)
';

COMMENT ON COLUMN ba_fuel_type_generation.bagenaso IS
    'BA annual solar net generation (MWh)
';

COMMENT ON COLUMN ba_fuel_type_generation.bagenagt IS
    'BA annual geothermal net generation (MWh)
';

COMMENT ON COLUMN ba_fuel_type_generation.bagenaof IS
    'BA annual other fossil net generation (MWh)
';

COMMENT ON COLUMN ba_fuel_type_generation.bagenaop IS
    'BA annual other unknown/ purchased fuel net generation (MWh)
';

COMMENT ON COLUMN ba_fuel_type_generation.bagenatn IS
    'BA annual total nonrenewables net generation (MWh)
';

COMMENT ON COLUMN ba_fuel_type_generation.bagenatr IS
    'BA annual total renewables net generation (MWh)
';

COMMENT ON COLUMN ba_fuel_type_generation.bagenath IS
    'BA annual total nonhydro renewables net generation (MWh)
';

COMMENT ON COLUMN ba_fuel_type_generation.bagenacy IS
    'BA annual total combustion net generation (MWh)
';

COMMENT ON COLUMN ba_fuel_type_generation.bagenacn IS
    'BA annual total noncombustion net generation (MWh)
';

ALTER TABLE ba_fuel_type_generation ADD CONSTRAINT ba_fuel_type_gen_pk PRIMARY KEY ( id );
-- added 
CREATE TABLE ba_nonbaseload_emission_rate (
    id       NUMBER NOT NULL,
    ba_id    NUMBER NOT NULL,
    banbnox  NUMBER,
    banbnxo  NUMBER,
    banbso2  NUMBER,
    banbco2  NUMBER,
    banbch4  NUMBER,
    banbn2o  NUMBER,
    banbc2e  NUMBER,
    banbhg   NUMBER,
    banbgncl NUMBER,
    banbgnol NUMBER,
    banbgngs NUMBER,
    banbgnnc NUMBER,
    banbgnhy NUMBER,
    banbgnbm NUMBER,
    banbgnwi NUMBER,
    banbgnso NUMBER,
    banbgngt NUMBER,
    banbgnof NUMBER,
    banbgnop NUMBER,
    banbclpr NUMBER,
    banbolpr NUMBER,
    banbgspr NUMBER,
    banbncpr NUMBER,
    banbhypr NUMBER,
    banbbmpr NUMBER,
    banbwipr NUMBER,
    banbsopr NUMBER,
    banbgtpr NUMBER,
    banbofpr NUMBER,
    banboppr NUMBER
);

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbnox IS
    'BA annual NOx non-baseload output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbnxo IS
    'BA ozone season NOx non-baseload output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbso2 IS
    'BA annual SO2 non-baseload output emission rate (lb/MWh) 
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbco2 IS
    'BA annual CO2 non-baseload output emission rate (lb/MWh) 
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbch4 IS
    'BA annual CH4 non-baseload output emission rate (lb/GWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbn2o IS
    'BA annual N2O non-baseload output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbc2e IS
    'BA annual CO2 equivalent non-baseload output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbhg IS
    'BA annual Hg non-baseload output emission rate (lb/MWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbgncl IS
    'BA annual nonbaseload coal net generation (MWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbgnol IS
    'BA annual nonbaseload oil net generation (MWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbgngs IS
    'BA annual nonbaseload gas net generation (MWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbgnnc IS
    'BA annual nonbaseload nuclear net generation (MWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbgnhy IS
    'BA annual nonbaseload hydro net generation (MWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbgnbm IS
    'BA annual nonbaseload biomass net generation (MWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbgnwi IS
    'BA annual nonbaseload wind net generation (MWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbgnso IS
    'BA annual nonbaseload solar net generation (MWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbgngt IS
    'BA annual nonbaseload geothermal net generation (MWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbgnof IS
    'BA annual nonbaseload other fossil net generation (MWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbgnop IS
    'BA annual nonbaseload other unknown/ purchased fuel net generation (MWh)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbclpr IS
    'BA nonbaseload coal generation percent (resource mix)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbolpr IS
    'BA nonbaseload oil generation percent (resource mix)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbgspr IS
    'BA nonbaseload gas generation percent (resource mix)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbncpr IS
    'BA nonbaseload nuclear generation percent (resource mix)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbhypr IS
    'BA nonbaseload hydro generation percent (resource mix)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbbmpr IS
    'BA nonbaseload biomass generation percent (resource mix)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbwipr IS
    'BA nonbaseload wind generation percent (resource mix)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbsopr IS
    'BA nonbaseload solar generation percent (resource mix)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbgtpr IS
    'BA nonbaseload geothermal generation percent (resource mix)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banbofpr IS
    'BA nonbaseload other fossil generation percent (resource mix)
';

COMMENT ON COLUMN ba_nonbaseload_emission_rate.banboppr IS
    'BA nonbaseload other unknown/ purchased fuel generation percent (resource mix)
';

--  ERROR: PK name length exceeds maximum allowed length(30) 
ALTER TABLE ba_nonbaseload_emission_rate ADD CONSTRAINT ba_nonbaseload_emission_rate_pk PRIMARY KEY ( id );

-- Added
CREATE TABLE ba_resource_mix (
    id         NUMBER NOT NULL,
    ba_id      NUMBER NOT NULL,
    baclpr     NUMBER,
    baolpr     NUMBER,
    bagspr     NUMBER,
    bancpr     NUMBER,
    bahypr     NUMBER,
    babmpr     NUMBER,
    bawipr     NUMBER,
    basopr     NUMBER,
    bagtpr     NUMBER,
    baofpr     NUMBER,
    baoppr     NUMBER,
    batnpr     NUMBER,
    batrpr     NUMBER,
    bathpr     NUMBER,
    bacypr     NUMBER,
    bacnpr     NUMBER,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

COMMENT ON COLUMN ba_resource_mix.baclpr IS
    'BA coal generation percent (resource mix)
';

COMMENT ON COLUMN ba_resource_mix.baolpr IS
    'BA oil generation percent (resource mix)
';

COMMENT ON COLUMN ba_resource_mix.bagspr IS
    'BA gas generation percent (resource mix)
';

COMMENT ON COLUMN ba_resource_mix.bancpr IS
    'BA nuclear generation percent (resource mix)
';

COMMENT ON COLUMN ba_resource_mix.bahypr IS
    'BA hydro generation percent (resource mix)
';

COMMENT ON COLUMN ba_resource_mix.babmpr IS
    'BA biomass generation percent (resource mix)
';

COMMENT ON COLUMN ba_resource_mix.bawipr IS
    'BA wind generation percent (resource mix)
';

COMMENT ON COLUMN ba_resource_mix.basopr IS
    'BA solar generation percent (resource mix)
';

COMMENT ON COLUMN ba_resource_mix.bagtpr IS
    'BA geothermal generation percent (resource mix)
';

COMMENT ON COLUMN ba_resource_mix.baofpr IS
    'BA other fossil generation percent (resource mix)
';

COMMENT ON COLUMN ba_resource_mix.baoppr IS
    'BA other unknown/ purchased fuel generation percent (resource mix)
';

COMMENT ON COLUMN ba_resource_mix.batnpr IS
    'BA total nonrenewables generation percent (resource mix)
';

COMMENT ON COLUMN ba_resource_mix.batrpr IS
    'BA total renewables generation percent (resource mix)
';

COMMENT ON COLUMN ba_resource_mix.bathpr IS
    'BA total nonhydro renewables generation percent (resource mix)
';

COMMENT ON COLUMN ba_resource_mix.bacypr IS
    'BA total combustion generation percent (resource mix)
';

COMMENT ON COLUMN ba_resource_mix.bacnpr IS
    'BA total noncombustion generation percent (resource mix)
';

ALTER TABLE ba_resource_mix ADD CONSTRAINT ba_resource_mix_pk PRIMARY KEY ( id );

-- CREATE TABLE balancing_auth (
--     bacode NUMBER NOT NULL,
--     baname VARCHAR2(500) NOT NULL
-- );

ALTER TABLE balancing_auth ADD CONSTRAINT balancing_auth_pk PRIMARY KEY ( bacode );
-- added

-- added
CREATE TABLE balancing_authority (
    ba_id      NUMBER NOT NULL,
    bacode     VARCHAR2(5) NOT NULL,
    baname     VARCHAR2(1000) NOT NULL,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

COMMENT ON COLUMN balancing_authority.bacode IS
    'BA_ID
';

COMMENT ON COLUMN balancing_authority.baname IS
    'Balancing Authority Name';

ALTER TABLE balancing_authority ADD CONSTRAINT balancing_auth_pkv1 PRIMARY KEY ( ba_id );

ALTER TABLE balancing_authority ADD CONSTRAINT balancing_auth__bacode_un UNIQUE ( bacode );

CREATE TABLE county (
    cntyname VARCHAR2(500) NOT NULL,
    fipscnty NUMBER NOT NULL
);

ALTER TABLE county ADD CONSTRAINT county_pk PRIMARY KEY ( fipscnty );
-- added
CREATE TABLE egrid_subrgn (
    subrgn_id  NUMBER NOT NULL,
    srname     VARCHAR2(500) NOT NULL,
    subrgn     VARCHAR2(4) NOT NULL,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

COMMENT ON COLUMN egrid_subrgn.srname IS
    'eGRID subregion name
';

COMMENT ON COLUMN egrid_subrgn.subrgn IS
    'eGRID subregion acronym';

ALTER TABLE egrid_subrgn ADD CONSTRAINT egrid_subregion_pk PRIMARY KEY ( subrgn_id );
-- added 
CREATE TABLE generator (
    seqgen22 NUMBER NOT NULL,
    genid    NUMBER NOT NULL,
    seqplt22 NUMBER NOT NULL,
    orispl   NUMBER NOT NULL,
    year     NUMBER(4),
    numblr   NUMBER,
    genstat  VARCHAR2(2),
    prmvr    VARCHAR2(2),
    fuelg1   VARCHAR2(5),
    namepcap NUMBER,
    cfact    NUMBER,
    genntan  NUMBER,
    genntoz  NUMBER,
    genersrc VARCHAR2(500),
    genyronl NUMBER(4),
    genyrret NUMBER(4)
);

ALTER TABLE generator ADD CONSTRAINT gen_pk PRIMARY KEY ( seqgen22 );

ALTER TABLE generator ADD CONSTRAINT genid__un UNIQUE ( genid );
-- added
CREATE TABLE nerc_region (
    nerc_abbrev VARCHAR2(4) NOT NULL,
    nerc        VARCHAR2(500) NOT NULL
);

COMMENT ON COLUMN nerc_region.nerc_abbrev IS
    'NERC region acronym';

COMMENT ON COLUMN nerc_region.nerc IS
    'Full name';

ALTER TABLE nerc_region ADD CONSTRAINT nerc_region_pk PRIMARY KEY ( nerc_abbrev );

-- added
CREATE TABLE plant (
    seqplt22    NUMBER NOT NULL,
    orispl      NUMBER(5) NOT NULL,
    pstatabb    VARCHAR2(2) NOT NULL,
    fipsst      NUMBER NOT NULL,
    pname       VARCHAR2(500) NOT NULL,
    oprcode     NUMBER NOT NULL,
    utlsrvid    NUMBER NOT NULL,
    sector_id   NUMBER NOT NULL,
    bacode      NUMBER NOT NULL,
    nerc        VARCHAR2(4) NOT NULL,
    fipscnty    NUMBER NOT NULL,
    lat         NUMBER,
    lon         NUMBER,
    numunt      NUMBER,
    numgen      NUMBER,
    plprmfl     VARCHAR2(3),
    plfuelct    VARCHAR2(10),
    coalflagind VARCHAR2(1),
    subrgn_id   NUMBER NOT NULL
);

ALTER TABLE plant ADD CONSTRAINT plant_pk PRIMARY KEY ( seqplt22 );

ALTER TABLE plant ADD CONSTRAINT plant_orispl_un UNIQUE ( orispl );

-- added
CREATE TABLE plant_distribution_sys (
    oprcode NUMBER NOT NULL,
    oprname VARCHAR2(500) NOT NULL
);

ALTER TABLE plant_distribution_sys ADD CONSTRAINT plant_distribution_sys_pk PRIMARY KEY ( oprcode );

-- added
CREATE TABLE plant_emission_rate (
    id         NUMBER NOT NULL,
    seqplt22   NUMBER NOT NULL,
    plnoxrta   NUMBER,
    plnoxra    NUMBER,
    plnoxro    NUMBER,
    plso2ra    NUMBER,
    plco2ra    NUMBER,
    plch4ra    NUMBER,
    pln2ora    NUMBER,
    plc2era    NUMBER,
    plhgra     NUMBER,
    plnoxcrt   NUMBER,
    plnoxcro   NUMBER,
    plso2crt   NUMBER,
    plco2crt   NUMBER,
    plch4crt   NUMBER,
    pln2ocrt   NUMBER,
    plc2ecrt   NUMBER,
    plhgcrt    NUMBER,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

ALTER TABLE plant_emission_rate ADD CONSTRAINT plant_emission_rate_pk PRIMARY KEY ( id );

-- added
CREATE TABLE plant_fuel_type_generation (
    id         NUMBER NOT NULL,
    seqplt22   NUMBER NOT NULL,
    plgenacl   NUMBER,
    plgenaol   NUMBER,
    plgenags   NUMBER,
    plgenanc   NUMBER,
    plgenahy   NUMBER,
    plgenabm   NUMBER,
    plgenawi   NUMBER,
    plgenaso   NUMBER,
    plgenagt   NUMBER,
    plgenaof   NUMBER,
    plgenaop   NUMBER,
    plgenacy   unknown 
--  ERROR: Datatype UNKNOWN is not allowed 
    ,
    plgenacn   unknown 
--  ERROR: Datatype UNKNOWN is not allowed 
    ,
    plgenatn   NUMBER,
    plgenatr   NUMBER,
    plgenath   NUMBER,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

ALTER TABLE plant_fuel_type_generation ADD CONSTRAINT plant_fuel_type_generation_pk PRIMARY KEY ( id );

-- added
CREATE TABLE plant_resource_mix (
    id         NUMBER NOT NULL,
    seqplt22   NUMBER NOT NULL,
    plclpr     NUMBER,
    plolpr     NUMBER,
    plgspr     NUMBER,
    plncpr     NUMBER,
    plhypr     NUMBER,
    plbmpr     NUMBER,
    plwipr     NUMBER,
    plsopr     NUMBER,
    plgtpr     NUMBER,
    plofpr     NUMBER,
    ploppr     NUMBER,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

ALTER TABLE plant_resource_mix ADD CONSTRAINT plant_resource_mix_pk PRIMARY KEY ( id );

-- added
CREATE TABLE sector (
    sector_id NUMBER NOT NULL,
    sector    VARCHAR2(100) NOT NULL
);

ALTER TABLE sector ADD CONSTRAINT sector_pk PRIMARY KEY ( sector_id );

--add
CREATE TABLE state (
    fipsst   NUMBER NOT NULL,
    pstatabb VARCHAR2(2) NOT NULL
);

ALTER TABLE state ADD CONSTRAINT state_pk PRIMARY KEY ( fipsst );
-- added
CREATE TABLE state_annual_combustion (
    id         NUMBER NOT NULL,
    fipsst     NUMBER NOT NULL,
    sthtian    NUMBER,
    sthtioz    NUMBER,
    sthtiant   NUMBER,
    sthtiozt   NUMBER,
    stngenan   NUMBER,
    stngenoz   NUMBER,
    stnoxan    NUMBER,
    stnoxoz    NUMBER,
    stso2an    NUMBER,
    stco2an    NUMBER,
    stch4an    NUMBER,
    stn2oan    NUMBER,
    stco2eqa   NUMBER,
    sthgan     NUMBER,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

COMMENT ON COLUMN state_annual_combustion.sthtian IS
    'State annual heat input from combustion (MMBtu)
';

COMMENT ON COLUMN state_annual_combustion.sthtioz IS
    'State ozone season heat input from combustion (MMBtu)
';

COMMENT ON COLUMN state_annual_combustion.sthtiant IS
    'State total annual heat input (MMBtu)
';

COMMENT ON COLUMN state_annual_combustion.sthtiozt IS
    'State total ozone season heat input (MMBtu)
';

COMMENT ON COLUMN state_annual_combustion.stngenan IS
    'State annual net generation (MWh)
';

COMMENT ON COLUMN state_annual_combustion.stngenoz IS
    'State ozone season net generation (MWh)
';

COMMENT ON COLUMN state_annual_combustion.stnoxan IS
    'State annual NOx emissions (tons)
';

COMMENT ON COLUMN state_annual_combustion.stnoxoz IS
    'State ozone season NOx emissions (tons)
';

COMMENT ON COLUMN state_annual_combustion.stso2an IS
    'State annual SO2 emissions (tons)
';

COMMENT ON COLUMN state_annual_combustion.stco2an IS
    'State annual CO2 emissions (tons)
';

COMMENT ON COLUMN state_annual_combustion.stch4an IS
    'State annual CH4 emissions (lbs)
';

COMMENT ON COLUMN state_annual_combustion.stn2oan IS
    'State annual N2O emissions (lbs)';

COMMENT ON COLUMN state_annual_combustion.stco2eqa IS
    'State annual CO2 equivalent emissions (tons)
';

COMMENT ON COLUMN state_annual_combustion.sthgan IS
    'State annual Hg emissions (lbs)
';

ALTER TABLE state_annual_combustion ADD CONSTRAINT sac_pk PRIMARY KEY ( id );
-- added
CREATE TABLE state_emission_rate (
    id         NUMBER NOT NULL,
    fipsst     NUMBER NOT NULL,
    stnoxrta   NUMBER,
    stnoxrto   NUMBER,
    stso2rta   NUMBER,
    stco2rta   NUMBER,
    stch4rta   NUMBER,
    stn2orta   NUMBER,
    stc2erta   NUMBER,
    sthgrta    NUMBER,
    stnoxra    NUMBER,
    stnoxro    NUMBER,
    stso2ra    NUMBER,
    stco2ra    NUMBER,
    stch4ra    NUMBER,
    stn2ora    NUMBER,
    stc2era    NUMBER,
    sthgra     NUMBER,
    stnoxcrt   NUMBER,
    stnoxcro   NUMBER,
    stso2crt   NUMBER,
    stco2crt   NUMBER,
    stch4crt   NUMBER,
    stn2ocrt   NUMBER,
    stc2ecrt   NUMBER,
    sthgcrt    NUMBER,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

ALTER TABLE state_emission_rate ADD CONSTRAINT state_emission_rate_pk PRIMARY KEY ( id );

-- added
CREATE TABLE state_fuel_type_emission_rate (
    id         NUMBER NOT NULL,
    fipsst     NUMBER NOT NULL,
    stcnoxrt   NUMBER,
    stonoxrt   NUMBER,
    stgnoxrt   NUMBER,
    stfsnxrt   NUMBER,
    stcnxort   NUMBER,
    stonxort   NUMBER,
    stgnxort   NUMBER,
    stfsnort   NUMBER,
    stcso2rt   NUMBER,
    stoso2rt   NUMBER,
    stgso2rt   NUMBER,
    stfss2rt   NUMBER,
    stcco2rt   NUMBER,
    stoco2rt   NUMBER,
    stgco2rt   NUMBER,
    stfsc2rt   NUMBER,
    stcch4rt   NUMBER,
    stoch4rt   NUMBER,
    stgch4rt   NUMBER,
    stfch4rt   NUMBER,
    stcn2ort   NUMBER,
    ston2ort   NUMBER,
    stgn2ort   NUMBER,
    stfn2ort   NUMBER,
    stcc2ert   NUMBER,
    stoc2ert   NUMBER,
    stgc2ert   NUMBER,
    stfsc2ert  NUMBER,
    stchgrt    NUMBER,
    stfshgrt   NUMBER,
    stcnoxr    NUMBER,
    stonoxr    NUMBER,
    stgnoxr    NUMBER,
    stfsnxr    NUMBER,
    stcnxor    NUMBER,
    stonxor    NUMBER,
    stgnxor    NUMBER,
    stfsnor    NUMBER,
    stcso2r    NUMBER,
    stoso2r    NUMBER,
    stgso2r    NUMBER,
    stfss2r    NUMBER,
    stcco2r    NUMBER,
    stoco2r    NUMBER,
    stgco2r    NUMBER,
    stfsc2r    NUMBER,
    stcch4r    NUMBER,
    stoch4r    NUMBER,
    stgch4r    NUMBER,
    stfch4r    NUMBER,
    stcn2or    NUMBER,
    ston2or    NUMBER,
    stgn2or    NUMBER,
    stfn2or    NUMBER,
    stcc2er    NUMBER,
    stoc2er    NUMBER,
    stgc2er    NUMBER,
    stfsc2er   NUMBER,
    stchgr     NUMBER,
    stfshgr    NUMBER,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

COMMENT ON COLUMN state_fuel_type_emission_rate.stcnoxrt IS
    'State annual NOx coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stonoxrt IS
    'State annual NOx oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stgnoxrt IS
    'State annual NOx gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stfsnxrt IS
    'State annual NOx fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stcnxort IS
    'State ozone season NOx coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stonxort IS
    'State ozone season NOx oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stgnxort IS
    'State ozone season NOx gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stfsnort IS
    'State ozone season NOx fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stcso2rt IS
    'State annual SO2 coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stoso2rt IS
    'State annual SO2 oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stgso2rt IS
    'State annual SO2 gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stfss2rt IS
    'State annual SO2 fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stcco2rt IS
    'State annual CO2 coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stoco2rt IS
    'State annual CO2 oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stgco2rt IS
    'State annual CO2 gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stfsc2rt IS
    'State annual CO2 fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stcch4rt IS
    'State annual CH4 coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stoch4rt IS
    'State annual CH4 oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stgch4rt IS
    'State annual CH4 gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stfch4rt IS
    'State annual CH4 fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stcn2ort IS
    'State annual N2O coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.ston2ort IS
    'State annual N2O oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stgn2ort IS
    'State annual N2O gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stfn2ort IS
    'State annual N2O fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stcc2ert IS
    'State annual CO2 equivalent coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stoc2ert IS
    'State annual CO2 equivalent oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stgc2ert IS
    'State annual CO2 equivalent gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stfsc2ert IS
    'State annual CO2 equivalent fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stchgrt IS
    'State annual Hg coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stfshgrt IS
    'State annual Hg fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stcnoxr IS
    'State annual NOx coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stonoxr IS
    'State annual NOx oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stgnoxr IS
    'State annual NOx gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stfsnxr IS
    'State annual NOx fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stcnxor IS
    'State ozone season NOx coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stonxor IS
    'State ozone season NOx oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stgnxor IS
    'State ozone season NOx gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stfsnor IS
    'State ozone season NOx fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stcso2r IS
    'State annual SO2 coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stoso2r IS
    'State annual SO2 oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stgso2r IS
    'State annual SO2 gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stfss2r IS
    'State annual SO2 fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stcco2r IS
    'State annual CO2 coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stoco2r IS
    'State annual CO2 oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stgco2r IS
    'State annual CO2 gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stfsc2r IS
    'State annual CO2 fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stcch4r IS
    'State annual CH4 coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stoch4r IS
    'State annual CH4 oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stgch4r IS
    'State annual CH4 gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stfch4r IS
    'State annual CH4 fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stcn2or IS
    'State annual N2O coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.ston2or IS
    'State annual N2O oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stgn2or IS
    'State annual N2O gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stfn2or IS
    'State annual N2O fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stcc2er IS
    'State annual CO2 equivalent coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stoc2er IS
    'State annual CO2 equivalent oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stgc2er IS
    'State annual CO2 equivalent gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stfsc2er IS
    'State annual CO2 equivalent fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stchgr IS
    'State annual Hg coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN state_fuel_type_emission_rate.stfshgr IS
    'State annual Hg fossil fuel input emission rate (lb/MMBtu)
';

--  ERROR: PK name length exceeds maximum allowed length(30) 
ALTER TABLE state_fuel_type_emission_rate ADD CONSTRAINT state_fuel_type_emission_rate_pk PRIMARY KEY ( id );

CREATE TABLE state_fuel_type_generation (
    id         NUMBER NOT NULL,
    fipsst     NUMBER NOT NULL,
    stgenacl   NUMBER,
    stgenaol   NUMBER,
    stgenaso   NUMBER,
    stgenagt   NUMBER,
    stgenaof   NUMBER,
    stgenaop   NUMBER,
    stgenatn   NUMBER,
    stgenatr   NUMBER,
    stgenath   NUMBER,
    stgenacy   NUMBER,
    stgenacn   NUMBER,
    stgenags   NUMBER,
    stgenanc   NUMBER,
    stgenahy   NUMBER,
    stgenabm   NUMBER,
    stgenawi   NUMBER,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

COMMENT ON COLUMN state_fuel_type_generation.stgenacl IS
    'State annual coal net generation (MWh)
';

COMMENT ON COLUMN state_fuel_type_generation.stgenaol IS
    'State annual oil net generation (MWh)
';

COMMENT ON COLUMN state_fuel_type_generation.stgenaso IS
    'State annual solar net generation (MWh)
';

COMMENT ON COLUMN state_fuel_type_generation.stgenagt IS
    'State annual geothermal net generation (MWh)
';

COMMENT ON COLUMN state_fuel_type_generation.stgenaof IS
    'State annual other fossil net generation (MWh)
';

COMMENT ON COLUMN state_fuel_type_generation.stgenaop IS
    'State annual other unknown/ purchased fuel net generation (MWh)
';

COMMENT ON COLUMN state_fuel_type_generation.stgenatn IS
    'State annual total nonrenewables net generation (MWh)
';

COMMENT ON COLUMN state_fuel_type_generation.stgenatr IS
    'State annual total renewables net generation (MWh)
';

COMMENT ON COLUMN state_fuel_type_generation.stgenath IS
    'State annual total nonhydro renewables net generation (MWh)
';

COMMENT ON COLUMN state_fuel_type_generation.stgenacy IS
    'State annual total combustion net generation (MWh)
';

COMMENT ON COLUMN state_fuel_type_generation.stgenacn IS
    'State annual total noncombustion net generation (MWh)
';

COMMENT ON COLUMN state_fuel_type_generation.stgenags IS
    'State annual gas net generation (MWh)
';

COMMENT ON COLUMN state_fuel_type_generation.stgenanc IS
    'State annual nuclear net generation (MWh)
';

COMMENT ON COLUMN state_fuel_type_generation.stgenahy IS
    'State annual hydro net generation (MWh)
';

COMMENT ON COLUMN state_fuel_type_generation.stgenabm IS
    'State annual biomass net generation (MWh)
';

COMMENT ON COLUMN state_fuel_type_generation.stgenawi IS
    'State annual wind net generation (MWh)
';

ALTER TABLE state_fuel_type_generation ADD CONSTRAINT state_fuel_type_generation_pk PRIMARY KEY ( id );

-- added
--  ERROR: Table name length exceeds maximum allowed length(30) 
CREATE TABLE state_nonbaseload_emission_rate (
    id         NUMBER NOT NULL,
    fipsst     NUMBER NOT NULL,
    "DATE"     TIMESTAMP WITH TIME ZONE NOT NULL,
    stnbnox    NUMBER,
    stnbnxo    NUMBER,
    stnbso2    NUMBER,
    stnbco2    NUMBER,
    stnbch4    NUMBER,
    stnbn2o    NUMBER,
    stnbc2e    NUMBER,
    stnbhg     NUMBER,
    stnbgncl   NUMBER,
    stnbgnol   NUMBER,
    stnbgngs   NUMBER,
    stnbgnnc   NUMBER,
    stnbgnhy   NUMBER,
    stnbgnbm   NUMBER,
    stnbgnwi   NUMBER,
    stnbgnso   NUMBER,
    stnbgngt   NUMBER,
    stnbgnof   NUMBER,
    stnbgnop   NUMBER,
    stnbclpr   NUMBER,
    stnbolpr   NUMBER,
    stnbgspr   NUMBER,
    stnbncpr   NUMBER,
    stnbhypr   NUMBER,
    stnbbmpr   NUMBER,
    stnbwipr   NUMBER,
    stnbsopr   NUMBER,
    stnbgtpr   NUMBER,
    stnbofpr   NUMBER,
    stnboppr   NUMBER,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbnox IS
    'State annual NOx non-baseload output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbnxo IS
    'State ozone season NOx non-baseload output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbso2 IS
    'State annual SO2 non-baseload output emission rate (lb/MWh) 
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbco2 IS
    'State annual CO2 non-baseload output emission rate (lb/MWh) 
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbch4 IS
    'State annual CH4 non-baseload output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbn2o IS
    'State annual N2O non-baseload output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbc2e IS
    'State annual CO2 equivalent non-baseload output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbhg IS
    'State annual Hg non-baseload output emission rate (lb/MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbgncl IS
    'State annual nonbaseload coal net generation (MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbgnol IS
    'State annual nonbaseload oil net generation (MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbgngs IS
    'State annual nonbaseload gas net generation (MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbgnnc IS
    'State annual nonbaseload nuclear net generation (MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbgnhy IS
    'State annual nonbaseload hydro net generation (MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbgnbm IS
    'State annual nonbaseload biomass net generation (MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbgnwi IS
    'State annual nonbaseload wind net generation (MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbgnso IS
    'State annual nonbaseload solar net generation (MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbgngt IS
    'State annual nonbaseload geothermal net generation (MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbgnof IS
    'State annual nonbaseload other fossil net generation (MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbgnop IS
    'State annual nonbaseload other unknown/ purchased fuel net generation (MWh)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbclpr IS
    'State nonbaseload coal generation percent (resource mix)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbolpr IS
    'State nonbaseload oil generation percent (resource mix)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbgspr IS
    'State nonbaseload gas generation percent (resource mix)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbncpr IS
    'State nonbaseload nuclear generation percent (resource mix)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbhypr IS
    'State nonbaseload hydro generation percent (resource mix)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbbmpr IS
    'State nonbaseload biomass generation percent (resource mix)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbwipr IS
    'State nonbaseload wind generation percent (resource mix)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbsopr IS
    'State nonbaseload solar generation percent (resource mix)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbgtpr IS
    'State nonbaseload geothermal generation percent (resource mix)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnbofpr IS
    'State nonbaseload other fossil generation percent (resource mix)
';

COMMENT ON COLUMN state_nonbaseload_emission_rate.stnboppr IS
    'State nonbaseload other unknown/ purchased fuel generation percent (resource mix)
';

--  ERROR: PK name length exceeds maximum allowed length(30) 
ALTER TABLE state_nonbaseload_emission_rate ADD CONSTRAINT state_nonbaseload_emission_rate_pk PRIMARY KEY ( id );

-- added
CREATE TABLE state_resource_mix (
    id           NUMBER NOT NULL,
    state_fipsst NUMBER NOT NULL,
    "DATE"       TIMESTAMP WITH TIME ZONE,
    stclpr       NUMBER,
    stolpr       NUMBER,
    stgspr       NUMBER,
    stncpr       NUMBER,
    sthypr       NUMBER,
    stbmpr       NUMBER,
    stwipr       NUMBER,
    stsopr       NUMBER,
    stgtpr       NUMBER,
    stofpr       NUMBER,
    stoppr       NUMBER,
    sttnpr       NUMBER,
    sttrpr       NUMBER,
    stthpr       NUMBER,
    stcypr       NUMBER,
    stcnpr       NUMBER,
    created_on   TIMESTAMP WITH TIME ZONE,
    created_by   VARCHAR2(500),
    updated_on   TIMESTAMP WITH TIME ZONE,
    updated_by   VARCHAR2(500)
);

COMMENT ON COLUMN state_resource_mix.stolpr IS
    'State oil generation percent (resource mix)
';

COMMENT ON COLUMN state_resource_mix.stgspr IS
    'State gas generation percent (resource mix)
';

COMMENT ON COLUMN state_resource_mix.stncpr IS
    'State nuclear generation percent (resource mix)
';

COMMENT ON COLUMN state_resource_mix.sthypr IS
    'State hydro generation percent (resource mix)
';

COMMENT ON COLUMN state_resource_mix.stbmpr IS
    'State biomass generation percent (resource mix)
';

COMMENT ON COLUMN state_resource_mix.stwipr IS
    'State wind generation percent (resource mix)
';

COMMENT ON COLUMN state_resource_mix.stsopr IS
    'State solar generation percent (resource mix)
';

COMMENT ON COLUMN state_resource_mix.stgtpr IS
    'State geothermal generation percent (resource mix)
';

COMMENT ON COLUMN state_resource_mix.stofpr IS
    'State other fossil generation percent (resource mix)';

COMMENT ON COLUMN state_resource_mix.stoppr IS
    'State other unknown/ purchased fuel generation percent (resource mix)
';

COMMENT ON COLUMN state_resource_mix.sttnpr IS
    'State total nonrenewables generation percent (resource mix)
';

COMMENT ON COLUMN state_resource_mix.sttrpr IS
    'State total renewables generation percent (resource mix)
';

COMMENT ON COLUMN state_resource_mix.stthpr IS
    'State total nonhydro renewables generation percent (resource mix)
';

COMMENT ON COLUMN state_resource_mix.stcypr IS
    'State total combustion generation percent (resource mix)
';

COMMENT ON COLUMN state_resource_mix.stcnpr IS
    'State total noncombustion generation percent (resource mix)
';

ALTER TABLE state_resource_mix ADD CONSTRAINT state_resource_mix_pk PRIMARY KEY ( id );
-- added
CREATE TABLE subrgn_annual_combustion (
    id         NUMBER NOT NULL,
    subrgn_id  NUMBER NOT NULL,
    srhtian    NUMBER,
    srhtioz    NUMBER,
    srhtiant   NUMBER,
    srhtiozt   NUMBER,
    srngenan   NUMBER,
    srngenoz   NUMBER,
    srnoxan    NUMBER,
    srnoxoz    NUMBER,
    srso2an    NUMBER,
    srco2an    NUMBER,
    srch4an    NUMBER,
    srn2oan    NUMBER,
    srco2eqa   NUMBER,
    srhgan     NUMBER,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

COMMENT ON COLUMN subrgn_annual_combustion.srhtian IS
    'eGRID subregion annual heat input from combustion (MMBtu)
';

COMMENT ON COLUMN subrgn_annual_combustion.srhtioz IS
    'eGRID subregion ozone season heat input from combustion (MMBtu)
';

COMMENT ON COLUMN subrgn_annual_combustion.srhtiant IS
    'eGRID subregion total annual heat input (MMBtu)';

COMMENT ON COLUMN subrgn_annual_combustion.srhtiozt IS
    'eGRID subregion total ozone season heat input (MMBtu)
';

COMMENT ON COLUMN subrgn_annual_combustion.srngenan IS
    'eGRID subregion annual net generation (MWh)
';

COMMENT ON COLUMN subrgn_annual_combustion.srngenoz IS
    'eGRID subregion ozone season net generation (MWh)';

COMMENT ON COLUMN subrgn_annual_combustion.srnoxan IS
    'eGRID subregion annual NOx emissions (tons)
';

COMMENT ON COLUMN subrgn_annual_combustion.srnoxoz IS
    'eGRID subregion ozone season NOx emissions (tons)
';

COMMENT ON COLUMN subrgn_annual_combustion.srso2an IS
    'eGRID subregion annual SO2 emissions (tons)
';

COMMENT ON COLUMN subrgn_annual_combustion.srco2an IS
    'eGRID subregion annual CO2 emissions (tons)
';

COMMENT ON COLUMN subrgn_annual_combustion.srch4an IS
    'eGRID subregion annual CH4 emissions (lbs)
';

COMMENT ON COLUMN subrgn_annual_combustion.srn2oan IS
    'eGRID subregion annual N2O emissions (lbs)
';

COMMENT ON COLUMN subrgn_annual_combustion.srco2eqa IS
    'eGRID subregion annual CO2 equivalent emissions (tons)
';

COMMENT ON COLUMN subrgn_annual_combustion.srhgan IS
    'eGRID subregion annual Hg emissions (lbs)
';

ALTER TABLE subrgn_annual_combustion ADD CONSTRAINT subrgn_annual_combustion_pk PRIMARY KEY ( id );

-- added
CREATE TABLE subrgn_emission_rate (
    id         NUMBER NOT NULL,
    subrgn_id  NUMBER NOT NULL,
    srnoxrta   NUMBER,
    srnoxrto   NUMBER,
    srso2rta   NUMBER,
    srco2rta   NUMBER,
    srch4rta   NUMBER,
    srn2orta   NUMBER,
    src2erta   NUMBER,
    srhgrta    NUMBER,
    srnoxra    NUMBER,
    srnoxro    NUMBER,
    srso2ra    NUMBER,
    srco2ra    NUMBER,
    srch4ra    NUMBER,
    srn2ora    NUMBER,
    src2era    NUMBER,
    srhgra     NUMBER,
    srnoxcrt   NUMBER,
    srnoxcro   NUMBER,
    srso2crt   NUMBER,
    srco2crt   NUMBER,
    srch4crt   NUMBER,
    srn2ocrt   NUMBER,
    src2ecrt   NUMBER,
    srhgcrt    NUMBER,
    created_on TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(500),
    updated_on TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR2(500)
);

COMMENT ON COLUMN subrgn_emission_rate.srnoxrta IS
    'eGRID subregion annual NOx total output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_emission_rate.srnoxrto IS
    'eGRID subregion ozone season NOx total output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_emission_rate.srso2rta IS
    'eGRID subregion annual SO2 total output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_emission_rate.srco2rta IS
    'eGRID subregion annual CO2 total output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_emission_rate.srch4rta IS
    'eGRID subregion annual CH4 total output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_emission_rate.srn2orta IS
    'eGRID subregion annual N2O total output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_emission_rate.src2erta IS
    'eGRID subregion annual CO2 equivalent total output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_emission_rate.srhgrta IS
    'eGRID subregion annual Hg total output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_emission_rate.srnoxra IS
    'eGRID subregion annual NOx input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_emission_rate.srnoxro IS
    'eGRID subregion ozone season NOx input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_emission_rate.srso2ra IS
    'eGRID subregion annual SO2 input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_emission_rate.srco2ra IS
    'eGRID subregion annual CO2 input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_emission_rate.srch4ra IS
    'eGRID subregion annual CH4 input emission rate (lb/MMBtu)';

COMMENT ON COLUMN subrgn_emission_rate.srn2ora IS
    'eGRID subregion annual N2O input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_emission_rate.src2era IS
    'eGRID subregion annual CO2 equivalent input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_emission_rate.srhgra IS
    'eGRID subregion annual Hg input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_emission_rate.srnoxcrt IS
    'eGRID subregion annual NOx combustion output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_emission_rate.srnoxcro IS
    'eGRID subregion ozone season NOx combustion output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_emission_rate.srso2crt IS
    'eGRID subregion annual SO2 combustion output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_emission_rate.srco2crt IS
    'eGRID subregion annual CO2 combustion output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_emission_rate.srch4crt IS
    'eGRID subregion annual CH4 combustion output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_emission_rate.srn2ocrt IS
    'eGRID subregion annual N2O combustion output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_emission_rate.src2ecrt IS
    'eGRID subregion annual CO2 equivalent combustion output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_emission_rate.srhgcrt IS
    'eGRID subregion annual Hg combustion output emission rate (lb/MWh)
';

ALTER TABLE subrgn_emission_rate ADD CONSTRAINT subrgn_emission_rate_pk PRIMARY KEY ( id );

CREATE TABLE subrgn_fuel_type_emission_rate (
    id                     NUMBER NOT NULL,
    egrid_subrgn_subrgn_id NUMBER NOT NULL,
    sronxort               NUMBER NOT NULL,
    srgnxort               NUMBER NOT NULL,
    srfsnort               NUMBER NOT NULL,
    srcso2rt               NUMBER NOT NULL,
    sroso2rt               NUMBER NOT NULL,
    srgso2rt               NUMBER NOT NULL,
    srfss2rt               NUMBER NOT NULL,
    srcco2rt               NUMBER NOT NULL,
    sroco2rt               NUMBER NOT NULL,
    srgco2rt               NUMBER NOT NULL,
    srfsc2rt               NUMBER NOT NULL,
    srcch4rt               NUMBER NOT NULL,
    sroch4rt               NUMBER NOT NULL,
    srgch4rt               NUMBER NOT NULL,
    srfch4rt               NUMBER NOT NULL,
    srcn2ort               NUMBER NOT NULL,
    sron2ort               NUMBER NOT NULL,
    srgn2ort               NUMBER NOT NULL,
    srfn2ort               NUMBER NOT NULL,
    srcc2ert               NUMBER NOT NULL,
    sroc2ert               NUMBER NOT NULL,
    srgc2ert               NUMBER NOT NULL,
    srfsc2ert              NUMBER NOT NULL,
    srchgrt                NUMBER NOT NULL,
    srfshgrt               NUMBER NOT NULL,
    srcnoxr                NUMBER NOT NULL,
    sronoxr                NUMBER NOT NULL,
    srgnoxr                NUMBER NOT NULL,
    srfsnxr                NUMBER NOT NULL,
    srcnxor                NUMBER NOT NULL,
    sronxor                NUMBER NOT NULL,
    srgnxor                NUMBER NOT NULL,
    srfsnor                NUMBER NOT NULL,
    srcso2r                NUMBER NOT NULL,
    sroso2r                NUMBER NOT NULL,
    srgso2r                NUMBER NOT NULL,
    srfss2r                NUMBER NOT NULL,
    srcco2r                NUMBER NOT NULL,
    sroco2r                NUMBER NOT NULL,
    srgco2r                NUMBER NOT NULL,
    srfsc2r                NUMBER NOT NULL,
    srcch4r                NUMBER NOT NULL,
    sroch4r                NUMBER NOT NULL,
    srgch4r                NUMBER NOT NULL,
    srfch4r                NUMBER NOT NULL,
    srcn2or                NUMBER NOT NULL,
    sron2or                NUMBER NOT NULL,
    srgn2or                NUMBER NOT NULL,
    srfn2or                NUMBER NOT NULL,
    srcc2er                NUMBER NOT NULL,
    sroc2er                NUMBER NOT NULL,
    srgc2er                NUMBER NOT NULL,
    srfsc2er               NUMBER NOT NULL,
    srchgr                 NUMBER NOT NULL,
    srfshgr                NUMBER NOT NULL
);

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.sronxort IS
    'eGRID subregion ozone season NOx oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srgnxort IS
    'eGRID subregion ozone season NOx gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srfsnort IS
    'eGRID subregion ozone season NOx fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srcso2rt IS
    'eGRID subregion annual SO2 coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.sroso2rt IS
    'eGRID subregion annual SO2 oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srgso2rt IS
    'eGRID subregion annual SO2 gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srfss2rt IS
    'eGRID subregion annual SO2 fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srcco2rt IS
    'eGRID subregion annual CO2 coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.sroco2rt IS
    'eGRID subregion annual CO2 oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srgco2rt IS
    'eGRID subregion annual CO2 gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srfsc2rt IS
    'eGRID subregion annual CO2 fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srcch4rt IS
    'eGRID subregion annual CH4 coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.sroch4rt IS
    'eGRID subregion annual CH4 oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srgch4rt IS
    'eGRID subregion annual CH4 gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srfch4rt IS
    'eGRID subregion annual CH4 fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srcn2ort IS
    'eGRID subregion annual N2O coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.sron2ort IS
    'eGRID subregion annual N2O oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srgn2ort IS
    'eGRID subregion annual N2O gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srfn2ort IS
    'eGRID subregion annual N2O fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srcc2ert IS
    'eGRID subregion annual CO2 equivalent coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.sroc2ert IS
    'eGRID subregion annual CO2 equivalent oil output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srgc2ert IS
    'eGRID subregion annual CO2 equivalent gas output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srfsc2ert IS
    'eGRID subregion annual CO2 equivalent fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srchgrt IS
    'eGRID subregion annual Hg coal output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srfshgrt IS
    'eGRID subregion annual Hg fossil fuel output emission rate (lb/MWh)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srcnoxr IS
    'eGRID subregion annual NOx coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.sronoxr IS
    'eGRID subregion annual NOx oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srgnoxr IS
    'eGRID subregion annual NOx gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srfsnxr IS
    'eGRID subregion annual NOx fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srcnxor IS
    'eGRID subregion ozone season NOx coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.sronxor IS
    'eGRID subregion ozone season NOx oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srgnxor IS
    'eGRID subregion ozone season NOx gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srfsnor IS
    'eGRID subregion ozone season NOx fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srcso2r IS
    'eGRID subregion annual SO2 coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.sroso2r IS
    'eGRID subregion annual SO2 oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srgso2r IS
    'eGRID subregion annual SO2 gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srfss2r IS
    'eGRID subregion annual SO2 fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srcco2r IS
    'eGRID subregion annual CO2 coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.sroco2r IS
    'eGRID subregion annual CO2 oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srgco2r IS
    'eGRID subregion annual CO2 gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srfsc2r IS
    'eGRID subregion annual CO2 fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srcch4r IS
    'eGRID subregion annual CH4 coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.sroch4r IS
    'eGRID subregion annual CH4 oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srgch4r IS
    'eGRID subregion annual CH4 gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srfch4r IS
    'eGRID subregion annual CH4 fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srcn2or IS
    'eGRID subregion annual N2O coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.sron2or IS
    'eGRID subregion annual N2O oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srgn2or IS
    'eGRID subregion annual N2O gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srfn2or IS
    'eGRID subregion annual N2O fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srcc2er IS
    'eGRID subregion annual CO2 equivalent coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.sroc2er IS
    'eGRID subregion annual CO2 equivalent oil input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srgc2er IS
    'eGRID subregion annual CO2 equivalent gas input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srfsc2er IS
    'eGRID subregion annual CO2 equivalent fossil fuel input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srchgr IS
    'eGRID subregion annual Hg coal input emission rate (lb/MMBtu)
';

COMMENT ON COLUMN subrgn_fuel_type_emission_rate.srfshgr IS
    'eGRID subregion annual Hg fossil fuel input emission rate (lb/MMBtu)
';

--  ERROR: PK name length exceeds maximum allowed length(30) 
ALTER TABLE subrgn_fuel_type_emission_rate ADD CONSTRAINT subrgn_fuel_type_emission_rate_pk PRIMARY KEY ( id );

-- CREATE TABLE utility (
--     utlsrvid NUMBER NOT NULL,
--     utlsrvnm VARCHAR2(500) NOT NULL
-- );

-- ALTER TABLE utility ADD CONSTRAINT utility_pk PRIMARY KEY ( utlsrvid );

ALTER TABLE ba_annual_combustion
    ADD CONSTRAINT ba_annual_combustion_fk FOREIGN KEY ( ba_id )
        REFERENCES balancing_authority ( ba_id )
            ON DELETE CASCADE;

ALTER TABLE ba_emission_rate
    ADD CONSTRAINT ba_emission_rate_fk FOREIGN KEY ( ba_id )
        REFERENCES balancing_authority ( ba_id )
            ON DELETE CASCADE;

ALTER TABLE ba_fuel_type_emission_rate
    ADD CONSTRAINT ba_fuel_type_emission_rate_fk FOREIGN KEY ( ba_id )
        REFERENCES balancing_authority ( ba_id )
            ON DELETE CASCADE;

ALTER TABLE ba_fuel_type_generation
    ADD CONSTRAINT ba_fuel_type_gen_fk FOREIGN KEY ( ba_id )
        REFERENCES balancing_authority ( ba_id )
            ON DELETE CASCADE;

ALTER TABLE ba_nonbaseload_emission_rate
    ADD CONSTRAINT ba_nonbaseload_emission_fk FOREIGN KEY ( ba_id )
        REFERENCES balancing_authority ( ba_id )
            ON DELETE CASCADE;

ALTER TABLE ba_resource_mix
    ADD CONSTRAINT ba_resource_mix_fk FOREIGN KEY ( ba_id )
        REFERENCES balancing_authority ( ba_id );

ALTER TABLE plant_fuel_type_generation
    ADD CONSTRAINT ftg_plant_fk FOREIGN KEY ( seqplt22 )
        REFERENCES plant ( seqplt22 )
            ON DELETE CASCADE;

ALTER TABLE generator
    ADD CONSTRAINT gen_plant_fk FOREIGN KEY ( seqplt22 )
        REFERENCES plant ( seqplt22 )
            ON DELETE CASCADE;

ALTER TABLE plant_emission_rate
    ADD CONSTRAINT ier_plant_fk FOREIGN KEY ( seqplt22 )
        REFERENCES plant ( seqplt22 )
            ON DELETE CASCADE;

ALTER TABLE plant
    ADD CONSTRAINT plant_balancing_auth_fk FOREIGN KEY ( bacode )
        REFERENCES balancing_auth ( bacode );

ALTER TABLE plant
    ADD CONSTRAINT plant_county_fk FOREIGN KEY ( fipscnty )
        REFERENCES county ( fipscnty );

ALTER TABLE plant
    ADD CONSTRAINT plant_egrid_subregion_fk FOREIGN KEY ( subrgn_id )
        REFERENCES egrid_subrgn ( subrgn_id );

ALTER TABLE plant
    ADD CONSTRAINT plant_nerc_region_fk FOREIGN KEY ( nerc )
        REFERENCES nerc_region ( nerc_abbrev );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE plant
    ADD CONSTRAINT plant_plant_distribution_sys_fk FOREIGN KEY ( oprcode )
        REFERENCES plant_distribution_sys ( oprcode );

ALTER TABLE plant
    ADD CONSTRAINT plant_sector_fk FOREIGN KEY ( sector_id )
        REFERENCES sector ( sector_id );

ALTER TABLE plant
    ADD CONSTRAINT plant_state_fk FOREIGN KEY ( fipsst )
        REFERENCES state ( fipsst )
            ON DELETE CASCADE;

ALTER TABLE plant
    ADD CONSTRAINT plant_utility_fk FOREIGN KEY ( utlsrvid )
        REFERENCES utility ( utlsrvid );

ALTER TABLE plant_resource_mix
    ADD CONSTRAINT resource_plant_fk FOREIGN KEY ( seqplt22 )
        REFERENCES plant ( seqplt22 )
            ON DELETE CASCADE;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE state_annual_combustion
    ADD CONSTRAINT state_annual_combustion_state_fk FOREIGN KEY ( fipsst )
        REFERENCES state ( fipsst )
            ON DELETE CASCADE;

ALTER TABLE state_emission_rate
    ADD CONSTRAINT state_emission_rate_fk FOREIGN KEY ( fipsst )
        REFERENCES state ( fipsst )
            ON DELETE CASCADE;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE state_fuel_type_emission_rate
    ADD CONSTRAINT state_fuel_type_emission_rate_fk FOREIGN KEY ( fipsst )
        REFERENCES state ( fipsst )
            ON DELETE CASCADE;

ALTER TABLE state_fuel_type_generation
    ADD CONSTRAINT state_fuel_type_generation_fk FOREIGN KEY ( fipsst )
        REFERENCES state ( fipsst )
            ON DELETE CASCADE;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE state_nonbaseload_emission_rate
    ADD CONSTRAINT state_nonbaseload_emission_rate_fk FOREIGN KEY ( fipsst )
        REFERENCES state ( fipsst )
            ON DELETE CASCADE;

ALTER TABLE state_resource_mix
    ADD CONSTRAINT state_resource_mix_fk FOREIGN KEY ( state_fipsst )
        REFERENCES state ( fipsst )
            ON DELETE CASCADE;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE subrgn_annual_combustion
    ADD CONSTRAINT subrgn_annual_combustion_egrid_subregion_fk FOREIGN KEY ( subrgn_id )
        REFERENCES egrid_subrgn ( subrgn_id )
            ON DELETE CASCADE;

ALTER TABLE subrgn_emission_rate
    ADD CONSTRAINT subrgn_emission_rate_fk FOREIGN KEY ( subrgn_id )
        REFERENCES egrid_subrgn ( subrgn_id )
            ON DELETE CASCADE;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE subrgn_fuel_type_emission_rate
    ADD CONSTRAINT subrgn_fuel_type_emission_rate_fk FOREIGN KEY ( egrid_subrgn_subrgn_id )
        REFERENCES egrid_subrgn ( subrgn_id )
            ON DELETE CASCADE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            29
-- CREATE INDEX                             0
-- ALTER TABLE                             59
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                  13
-- WARNINGS                                 0
