# Generated by Django 5.1.5 on 2025-01-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baannualcombustion',
            name='bahtian',
            field=models.FloatField(blank=True, db_comment='BA annual heat input from combustion (MMBtu)', null=True),
        ),
    ]
