# Generated by Django 5.1.5 on 2025-04-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0002_baemissionrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsNonBaseloadValues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usnbnox', models.FloatField(blank=True, null=True)),
                ('usnbnxo', models.FloatField(blank=True, null=True)),
                ('usnbso2', models.FloatField(blank=True, null=True)),
                ('usnbco2', models.FloatField(blank=True, null=True)),
                ('usnbch4', models.FloatField(blank=True, null=True)),
                ('usnbn2o', models.FloatField(blank=True, null=True)),
                ('usnbc2e', models.FloatField(blank=True, null=True)),
                ('usnbhg', models.FloatField(blank=True, null=True)),
                ('usnbgncl', models.FloatField(blank=True, null=True)),
                ('usnbgnol', models.FloatField(blank=True, null=True)),
                ('usnbgngs', models.FloatField(blank=True, null=True)),
                ('usnbgnnc', models.FloatField(blank=True, null=True)),
                ('usnbgnhy', models.FloatField(blank=True, null=True)),
                ('usnbgnbm', models.FloatField(blank=True, null=True)),
                ('usnbgnwi', models.FloatField(blank=True, null=True)),
                ('usnbgnso', models.FloatField(blank=True, null=True)),
                ('usnbgngt', models.FloatField(blank=True, null=True)),
                ('usnbgnof', models.FloatField(blank=True, null=True)),
                ('usnbgnop', models.FloatField(blank=True, null=True)),
                ('usnbclpr', models.FloatField(blank=True, null=True)),
                ('usnbolpr', models.FloatField(blank=True, null=True)),
                ('usnbgspr', models.FloatField(blank=True, null=True)),
                ('usnbncpr', models.FloatField(blank=True, null=True)),
                ('usnbhypr', models.FloatField(blank=True, null=True)),
                ('usnbbmpr', models.FloatField(blank=True, null=True)),
                ('usnbwipr', models.FloatField(blank=True, null=True)),
                ('usnbsopr', models.FloatField(blank=True, null=True)),
                ('usnbgtpr', models.FloatField(blank=True, null=True)),
                ('usnbofpr', models.FloatField(blank=True, null=True)),
                ('usnboppr', models.FloatField(blank=True, null=True)),
                ('usnamepcap', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'us_nonbaseload_values',
            },
        ),
        migrations.RenameModel(
            old_name='BaNonBaseloadEmissionRate',
            new_name='BaNonBaseloadValues',
        ),
        migrations.RenameModel(
            old_name='NercNonBaseloadEmissionRate',
            new_name='NercNonBaseloadValues',
        ),
        migrations.RenameModel(
            old_name='StateNonBaseloadEmissionRate',
            new_name='StateNonBaseloadValues',
        ),
        migrations.RenameModel(
            old_name='SubrgnNonBaseloadEmissionRate',
            new_name='SubrgnNonBaseloadValues',
        ),
        migrations.DeleteModel(
            name='UsNonBaseloadEmissionRate',
        ),
        migrations.AddField(
            model_name='usemissionrate',
            name='usnamepcap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usfueltypeemissionrate',
            name='usnamepcap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usfueltypegeneration',
            name='usnamepcap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usresourcemix',
            name='usnamepcap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baadjustedvalues',
            name='bahgan',
            field=models.FloatField(blank=True, null=True),
        ), 
        migrations.AddConstraint(
            model_name='usadjustedvalues',
            constraint=models.UniqueConstraint(fields=('usnamepcap', 'year'), name='usadjustedvalues_composite_pk'),
        ),
        migrations.AddConstraint(
            model_name='usemissionrate',
            constraint=models.UniqueConstraint(fields=('usnamepcap', 'year'), name='usemissionrate_composite_pk'),
        ),
        migrations.AddConstraint(
            model_name='usfueltypeemissionrate',
            constraint=models.UniqueConstraint(fields=('usnamepcap', 'year'), name='usfueltypeemissionrate_composite_pk'),
        ),
        migrations.AddConstraint(
            model_name='usfueltypegeneration',
            constraint=models.UniqueConstraint(fields=('usnamepcap', 'year'), name='usfueltypegeneration_composite_pk'),
        ),
        migrations.AddConstraint(
            model_name='usresourcemix',
            constraint=models.UniqueConstraint(fields=('usnamepcap', 'year'), name='usresourcemix_composite_pk'),
        ),
        migrations.AlterModelTable(
            name='banonbaseloadvalues',
            table='ba_nonbaseload_values',
        ),
        migrations.AlterModelTable(
            name='nercnonbaseloadvalues',
            table='nerc_nonbaseload_values',
        ),
        migrations.AlterModelTable(
            name='statenonbaseloadvalues',
            table='state_nonbaseload_values',
        ),
        migrations.AlterModelTable(
            name='subrgnnonbaseloadvalues',
            table='subrgn_nonbaseload_values',
        ),
        migrations.AddConstraint(
            model_name='usnonbaseloadvalues',
            constraint=models.UniqueConstraint(fields=('usnamepcap', 'year'), name='usnonbaseloadvalues_composite_pk'),
        ),
    ]
