# Generated by Django 5.1.5 on 2025-01-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0002_alter_baannualcombustion_bahtian'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
