# Generated by Django 5.1.5 on 2025-01-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0003_plant_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='banonbaseloademissionrate',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baresourcemix',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
