# Generated by Django 5.1.5 on 2025-04-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0003_usnonbaseloadvalues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='us',
            name='year',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
