# Generated by Django 5.1.5 on 2025-01-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0004_banonbaseloademissionrate_year_baresourcemix_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='banonbaseloademissionrate',
            name='banboppr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
