# Generated by Django 5.1.5 on 2025-04-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0004_us_year'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='us',
            constraint=models.UniqueConstraint(fields=('usnamepcap', 'year'), name='us_composite_pk'),
        ),
    ]
