# Generated by Django 5.1.5 on 2025-01-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0005_banonbaseloademissionrate_banboppr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='fuelg1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='generator',
            name='genersrc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='generator',
            name='genid',
            field=models.FloatField(unique=True),
        ),
        migrations.AlterField(
            model_name='generator',
            name='genstat',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='generator',
            name='prmvr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='generator',
            name='seqgen',
            field=models.FloatField(),
        ),
    ]
