# Generated by Django 5.1.5 on 2025-04-08 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0005_us_us_composite_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='fuelu1',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='hrsop',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='untopst',
        ),
        migrations.AddField(
            model_name='unit',
            name='sequnt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UnitUnadjustedValues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unitid', models.CharField(max_length=100)),
                ('prmvr', models.CharField(blank=True, max_length=2, null=True)),
                ('untopst', models.CharField(blank=True, max_length=2, null=True)),
                ('fuelu1', models.CharField(blank=True, max_length=6, null=True)),
                ('hrsop', models.FloatField(blank=True, null=True)),
                ('htian', models.FloatField(blank=True, null=True)),
                ('htioz', models.FloatField(blank=True, null=True)),
                ('noxan', models.FloatField(blank=True, null=True)),
                ('noxoz', models.FloatField(blank=True, null=True)),
                ('so2an', models.FloatField(blank=True, null=True)),
                ('co2an', models.FloatField(blank=True, null=True)),
                ('hgan', models.FloatField(blank=True, null=True)),
                ('htiansrc', models.CharField(blank=True, max_length=200, null=True)),
                ('htiozsrc', models.CharField(blank=True, max_length=200, null=True)),
                ('noxansrc', models.CharField(blank=True, max_length=200, null=True)),
                ('noxozsrc', models.CharField(blank=True, max_length=200, null=True)),
                ('so2src', models.CharField(blank=True, max_length=200, null=True)),
                ('co2src', models.CharField(blank=True, max_length=200, null=True)),
                ('hgsrc', models.CharField(blank=True, max_length=200, null=True)),
                ('so2ctldc', models.CharField(blank=True, max_length=10, null=True)),
                ('noxctldv', models.CharField(blank=True, max_length=200, null=True)),
                ('hgctldv', models.CharField(blank=True, max_length=200, null=True)),
                ('untyronl', models.IntegerField(blank=True, null=True)),
                ('stackht', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('orispl', models.ForeignKey(db_column='orispl', on_delete=django.db.models.deletion.CASCADE, to='egrid.plant')),
            ],
            options={
                'db_table': 'unit_unadjusted_values',
                'constraints': [models.UniqueConstraint(fields=('unitid', 'orispl', 'prmvr', 'year'), name='unitunadjustedvalues_composite_pk')],
            },
        ),
    ]
