# Generated by Django 5.1.5 on 2025-01-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0006_alter_generator_fuelg1_alter_generator_genersrc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='orispl',
            field=models.IntegerField(unique=True),
        ),
    ]
