# Generated by Django 5.1.5 on 2025-04-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0006_remove_unit_fuelu1_remove_unit_hrsop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nercregion',
            old_name='nerc_name',
            new_name='nercname',
        ),
    ]
