# Generated by Django 5.1.5 on 2025-04-08 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0007_rename_nerc_name_nercregion_nercname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nercadjustedvalues',
            name='nerc',
            field=models.ForeignKey(db_column='nerc', on_delete=django.db.models.deletion.CASCADE, to='egrid.nercregion', to_field='nerc'),
        ),
        migrations.AlterField(
            model_name='nercemissionrate',
            name='nerc',
            field=models.ForeignKey(db_column='nerc', on_delete=django.db.models.deletion.CASCADE, to='egrid.nercregion', to_field='nerc'),
        ),
        migrations.AlterField(
            model_name='nercfueltypeemissionrate',
            name='nerc',
            field=models.ForeignKey(db_column='nerc', on_delete=django.db.models.deletion.CASCADE, to='egrid.nercregion', to_field='nerc'),
        ),
        migrations.AlterField(
            model_name='nercfueltypegeneration',
            name='nerc',
            field=models.ForeignKey(db_column='nerc', on_delete=django.db.models.deletion.CASCADE, to='egrid.nercregion', to_field='nerc'),
        ),
        migrations.AlterField(
            model_name='nercnonbaseloadvalues',
            name='nerc',
            field=models.ForeignKey(db_column='nerc', on_delete=django.db.models.deletion.CASCADE, to='egrid.nercregion', to_field='nerc'),
        ),
        migrations.AlterField(
            model_name='nercresourcemix',
            name='nerc',
            field=models.ForeignKey(db_column='nerc', on_delete=django.db.models.deletion.CASCADE, to='egrid.nercregion', to_field='nerc'),
        ),
    ]
