# Generated by Django 5.1.5 on 2025-01-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0007_alter_plant_orispl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='seqgen',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
