# Generated by Django 5.1.5 on 2025-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0008_alter_generator_seqgen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='genid',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
    ]
