# Generated by Django 5.1.5 on 2025-01-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0009_alter_generator_genid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generator',
            name='cfact',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='fuelg1',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='genersrc',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='genntan',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='genntoz',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='genstat',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='genyronl',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='genyrret',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='namepcap',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='numblr',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='prmvr',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='year',
        ),
    ]
