# Generated by Django 5.1.5 on 2025-04-08 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0009_alter_statefueltypeemissionrate_fipsst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateadjustedvalues',
            name='fipsst',
            field=models.ForeignKey(db_column='fipsst', on_delete=django.db.models.deletion.CASCADE, to='egrid.state', to_field='fipsst'),
        ),
        migrations.AlterField(
            model_name='stateemissionrate',
            name='fipsst',
            field=models.ForeignKey(db_column='fipsst', on_delete=django.db.models.deletion.CASCADE, to='egrid.state', to_field='fipsst'),
        ),
        migrations.AlterField(
            model_name='statefueltypegeneration',
            name='fipsst',
            field=models.ForeignKey(db_column='fipsst', on_delete=django.db.models.deletion.CASCADE, to='egrid.state', to_field='fipsst'),
        ),
    ]
