# Generated by Django 5.1.5 on 2025-01-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0010_remove_generator_cfact_remove_generator_fuelg1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='genid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='generator',
            constraint=models.UniqueConstraint(fields=('genid', 'orispl'), name='unique_genid_orispl'),
        ),
    ]
