# Generated by Django 5.1.5 on 2025-01-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0011_alter_generator_genid_generator_unique_genid_orispl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='genid',
            field=models.CharField(blank=True, null=True),
        ),
    ]
