# Generated by Django 5.1.5 on 2025-04-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0011_unitunadjustedvalues_so2ctldv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitunadjustedvalues',
            name='so2ctldc',
        ),
        migrations.AlterField(
            model_name='unitunadjustedvalues',
            name='so2ctldv',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
