# Generated by Django 5.1.5 on 2025-02-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0012_alter_generator_genid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nercregion',
            name='nerc_abbrev',
        ),
        migrations.AddField(
            model_name='nercregion',
            name='nerc_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nercregion',
            name='nerc',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
