# Generated by Django 5.1.5 on 2025-04-15 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0013_alter_plantadjustedvalues_orispl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdistributionsys',
            name='orispl',
            field=models.ForeignKey(db_column='orispl', default=1, on_delete=django.db.models.deletion.CASCADE, to='egrid.plant', to_field='orispl'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unitunadjustedvalues',
            name='untopst',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
