# Generated by Django 5.1.5 on 2025-02-11 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0013_remove_nercregion_nerc_abbrev_nercregion_nerc_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateannualcombustion',
            name='fipsst',
            field=models.ForeignKey(db_column='fipsst', on_delete=django.db.models.deletion.CASCADE, to='egrid.state'),
        ),
    ]
