# Generated by Django 5.1.5 on 2025-04-16 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0014_plantdistributionsys_orispl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='orispl',
            field=models.ForeignKey(db_column='orispl', on_delete=django.db.models.deletion.CASCADE, to='egrid.plant', to_field='orispl'),
        ),
    ]
