# Generated by Django 5.1.5 on 2025-02-11 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0014_alter_stateannualcombustion_fipsst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateemissionrate',
            name='fipsst',
            field=models.ForeignKey(db_column='fipsst', on_delete=django.db.models.deletion.CASCADE, to='egrid.state'),
        ),
        migrations.AlterField(
            model_name='statefueltypeemissionrate',
            name='fipsst',
            field=models.ForeignKey(db_column='fipsst', on_delete=django.db.models.deletion.CASCADE, to='egrid.state'),
        ),
        migrations.AlterField(
            model_name='statefueltypegeneration',
            name='fipsst',
            field=models.ForeignKey(db_column='fipsst', on_delete=django.db.models.deletion.CASCADE, to='egrid.state'),
        ),
        migrations.AlterField(
            model_name='statenonbaseloademissionrate',
            name='fipsst',
            field=models.ForeignKey(db_column='fipsst', on_delete=django.db.models.deletion.CASCADE, to='egrid.state'),
        ),
        migrations.AlterField(
            model_name='stateresourcemix',
            name='fipsst',
            field=models.ForeignKey(db_column='fipsst', on_delete=django.db.models.deletion.CASCADE, to='egrid.state'),
        ),
    ]
