# Generated by Django 5.1.5 on 2025-02-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0015_alter_stateemissionrate_fipsst_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EgridSubrgn',
            new_name='Subregion',
        ),
        migrations.AlterModelTable(
            name='subregion',
            table='subregion',
        ),
    ]
