# Generated by Django 5.1.5 on 2025-04-17 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0016_alter_unitunadjustedvalues_orispl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='bacode',
            field=models.ForeignKey(db_column='bacode', on_delete=django.db.models.deletion.CASCADE, to='egrid.balancingauthority'),
        ),
    ]
