# Generated by Django 5.1.5 on 2025-02-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0016_rename_egridsubrgn_subregion_alter_subregion_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subregion',
            name='srname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='subrgn',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True),
        ),
    ]
