# Generated by Django 5.1.5 on 2025-02-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0017_alter_subregion_srname_alter_subregion_subrgn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subregion',
            name='subrgn',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
