# Generated by Django 5.1.5 on 2025-02-11 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0018_alter_subregion_subrgn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='subrgn_id',
        ),
        migrations.RemoveField(
            model_name='subrgnannualcombustion',
            name='subrgn_id',
        ),
        migrations.RemoveField(
            model_name='subrgnemissionrate',
            name='subrgn_id',
        ),
        migrations.RemoveField(
            model_name='subrgnfueltypeemissionrate',
            name='subrgn_id',
        ),
        migrations.AddField(
            model_name='plant',
            name='subrgn',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='subrgnannualcombustion',
            name='subrgn',
            field=models.ForeignKey(db_column='subrgn', default=99, on_delete=django.db.models.deletion.CASCADE, to='egrid.subregion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subrgnemissionrate',
            name='subrgn',
            field=models.ForeignKey(db_column='subrgn', default=99, on_delete=django.db.models.deletion.CASCADE, to='egrid.subregion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subrgnfueltypeemissionrate',
            name='subrgn',
            field=models.ForeignKey(db_column='subrgn', default=99, on_delete=django.db.models.deletion.CASCADE, to='egrid.subregion'),
            preserve_default=False,
        ),
    ]
