# Generated by Django 5.1.5 on 2025-04-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0019_baemissionrate_ber_unique_bacode_year_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bafueltypegeneration',
            constraint=models.UniqueConstraint(fields=('bacode', 'year'), name='ba_fuel_type_gen_unique_bacode_year'),
        ),
        migrations.AddConstraint(
            model_name='banonbaseloadvalues',
            constraint=models.UniqueConstraint(fields=('bacode', 'year'), name='ba_nonbaseload_values_unique_bacode_year'),
        ),
        migrations.AddConstraint(
            model_name='baresourcemix',
            constraint=models.UniqueConstraint(fields=('bacode', 'year'), name='ba_resource_mix_unique_bacode_year'),
        ),
    ]
