# Generated by Django 5.1.5 on 2025-02-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0019_remove_plant_subrgn_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unitid', models.CharField(max_length=100)),
                ('prmvr', models.CharField(blank=True, max_length=2, null=True)),
                ('untopst', models.CharField(blank=True, max_length=2, null=True)),
                ('camdflag', models.CharField(blank=True, max_length=50, null=True)),
                ('prgcode', models.CharField(blank=True, max_length=4000, null=True)),
                ('botfirty', models.CharField(blank=True, max_length=255, null=True)),
                ('numgen', models.IntegerField(blank=True, null=True)),
                ('fuelu1', models.CharField(blank=True, max_length=6, null=True)),
                ('hrsop', models.FloatField(blank=True, null=True)),
                ('orispl', models.ForeignKey(db_column='orispl', on_delete=django.db.models.deletion.CASCADE, to='egrid.plant')),
            ],
            options={
                'db_table': 'unit',
                'constraints': [models.UniqueConstraint(fields=('unitid', 'orispl'), name='unit_composite_pk')],
            },
        ),
    ]
