# Generated by Django 5.1.5 on 2025-04-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0020_bafueltypegeneration_ba_fuel_type_gen_unique_bacode_year_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plantadjustedvalues',
            constraint=models.UniqueConstraint(fields=('orispl', 'year'), name='plant_adjusted_values_unique_bacode_year'),
        ),
        migrations.AddConstraint(
            model_name='plantemissionrate',
            constraint=models.UniqueConstraint(fields=('orispl', 'year'), name='plant_emission_rate_unique_bacode_year'),
        ),
        migrations.AddConstraint(
            model_name='plantfueltypegeneration',
            constraint=models.UniqueConstraint(fields=('orispl', 'year'), name='plant_fuel_type_gen_unique_bacode_year'),
        ),
        migrations.AddConstraint(
            model_name='plantresourcemix',
            constraint=models.UniqueConstraint(fields=('orispl', 'year'), name='plant_resource_mix_unique_bacode_year'),
        ),
        migrations.AddConstraint(
            model_name='plantunadjustedvalues',
            constraint=models.UniqueConstraint(fields=('orispl', 'year'), name='plant_unadjusted_values_unique_bacode_year'),
        ),
    ]
