# Generated by Django 5.1.5 on 2025-02-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0020_unit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unit',
            name='unit_composite_pk',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='camdflag',
            new_name='capdflag',
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('unitid', 'orispl', 'prmvr'), name='unit_composite_pk'),
        ),
    ]
