# Generated by Django 5.2 on 2025-04-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "egrid",
            "0021_plantadjustedvalues_plant_adjusted_values_unique_bacode_year_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plantunadjustedvalues",
            name="unco2src",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
