# Generated by Django 5.1.5 on 2025-04-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0021_remove_unit_unit_composite_pk_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='generator',
            name='unique_genid_orispl',
        ),
        migrations.AlterField(
            model_name='generator',
            name='orispl',
            field=models.IntegerField(unique=True),
        ),
    ]
