# Generated by Django 5.1.5 on 2025-04-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0022_remove_generator_unique_genid_orispl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='orispl',
            field=models.IntegerField(),
        ),
    ]
