# Generated by Django 5.1.5 on 2025-04-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0023_alter_generator_orispl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='plant_name',
            new_name='pname',
        ),
    ]
