# Generated by Django 5.1.5 on 2025-07-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0024_remove_baemissionrate_ber_unique_bacode_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='capfac',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
