# Generated by Django 5.2 on 2025-04-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0024_remove_baemissionrate_ber_unique_bacode_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generator",
            name="seqgen",
        ),
        migrations.AddField(
            model_name="generation",
            name="seqgen",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
