# Generated by Django 5.2 on 2025-04-25 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0024_remove_baemissionrate_ber_unique_bacode_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="state",
            name="stnamepcap",
        ),
        migrations.AlterField(
            model_name="plant",
            name="fipsst",
            field=models.ForeignKey(
                db_column="fipsst",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="egrid.state",
                to_field="fipsst",
            ),
            preserve_default=False,
        ),
    ]
