# Generated by Django 5.1.5 on 2025-04-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0024_rename_plant_name_plant_pname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='sector_id',
            new_name='sector',
        ),
    ]
