# Generated by Django 5.1.5 on 2025-04-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0025_rename_sector_id_plant_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='year',
        ),
    ]
