# Generated by Django 5.2 on 2025-04-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0025_remove_state_stnamepcap_alter_plant_fipsst"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plant",
            name="pstatabb",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="seqplt",
        ),
    ]
