# Generated by Django 5.2 on 2025-04-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0025_remove_generator_seqgen_generation_seqgen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="numgen",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="sequnt",
        ),
        migrations.AddField(
            model_name="unitunadjustedvalues",
            name="numgen",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unitunadjustedvalues",
            name="sequnt",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
