# Generated by Django 5.2 on 2025-04-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0026_remove_unit_numgen_remove_unit_sequnt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generation",
            name="seqgen",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="seqplt",
        ),
        migrations.RemoveField(
            model_name="unitunadjustedvalues",
            name="sequnt",
        ),
    ]
