# Generated by Django 5.1.5 on 2025-04-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0026_remove_plant_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='coalflagind',
            new_name='coalflag',
        ),
    ]
