# Generated by Django 5.2 on 2025-04-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0026_remove_plant_pstatabb_remove_plant_seqplt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subregion",
            name="srnamepcap",
        ),
        migrations.AddField(
            model_name="subrgnadjustedvalues",
            name="srnamepcap",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
