# Generated by Django 5.1.5 on 2025-04-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0027_rename_coalflagind_plant_coalflag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='seqplt',
            new_name='sequnt',
        ),
    ]
