# Generated by Django 5.2 on 2025-04-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0027_remove_generation_seqgen_remove_plant_seqplt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitunadjustedvalues",
            name="so2ctldv",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
