# Generated by Django 5.2 on 2025-04-25 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0027_remove_subregion_srnamepcap_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="subrgn",
            field=models.ForeignKey(
                db_column="subrgn",
                on_delete=django.db.models.deletion.CASCADE,
                to="egrid.subregion",
            ),
        ),
    ]
