# Generated by Django 5.1.5 on 2025-04-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0028_rename_seqplt_plant_sequnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baannualcombustion',
            name='bacode',
            field=models.CharField(max_length=10),
        ),
    ]
