# Generated by Django 5.2 on 2025-04-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0028_alter_unitunadjustedvalues_so2ctldv"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nercregion",
            name="nrnamepcap",
        ),
    ]
