# Generated by Django 5.2 on 2025-04-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0028_alter_plant_subrgn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="subrgn",
            field=models.CharField(max_length=4),
        ),
    ]
