# Generated by Django 5.1.5 on 2025-07-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0029_plant_cntyname_alter_plant_fipscnty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='fipscnty',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
