# Generated by Django 5.2 on 2025-04-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0029_remove_nercregion_nrnamepcap"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balancingauthority",
            name="banamepcap",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="namepcap",
        ),
        migrations.AddField(
            model_name="plantadjustedvalues",
            name="namepcap",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
