# Generated by Django 5.1.5 on 2025-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0029_alter_baannualcombustion_bacode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baannualcombustion',
            name='bacode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='balancingauthority',
            name='bacode',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
