# Generated by Django 5.2 on 2025-04-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0029_alter_plant_subrgn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plant",
            name="namepcap",
        ),
        migrations.AddField(
            model_name="plantadjustedvalues",
            name="namepcap",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
