# Generated by Django 5.2 on 2025-04-23 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0030_remove_balancingauthority_banamepcap_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantUtility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("utlsrvid", models.IntegerField(blank=True, null=True, unique=True)),
                ("utlsrvname", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "plant_utility",
            },
        ),
        migrations.DeleteModel(
            name="County",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="pstatabb",
        ),
        migrations.RemoveField(
            model_name="plantdistributionsys",
            name="orispl",
        ),
        migrations.RemoveField(
            model_name="state",
            name="stnamepcap",
        ),
        migrations.RemoveField(
            model_name="subregion",
            name="srnamepcap",
        ),
        migrations.AlterField(
            model_name="plant",
            name="fipsst",
            field=models.ForeignKey(
                db_column="fipsst",
                on_delete=django.db.models.deletion.CASCADE,
                to="egrid.state",
                to_field="fipsst",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="nerc",
            field=models.ForeignKey(
                db_column="nerc",
                on_delete=django.db.models.deletion.CASCADE,
                to="egrid.nercregion",
                to_field="nerc",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="oprcode",
            field=models.ForeignKey(
                db_column="oprcode",
                on_delete=django.db.models.deletion.CASCADE,
                to="egrid.plantdistributionsys",
                to_field="oprcode",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="subrgn",
            field=models.ForeignKey(
                db_column="subrgn",
                on_delete=django.db.models.deletion.CASCADE,
                to="egrid.subregion",
            ),
        ),
        migrations.AlterField(
            model_name="plantdistributionsys",
            name="oprcode",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="utlsrvid",
            field=models.ForeignKey(
                db_column="utlsrvid",
                on_delete=django.db.models.deletion.CASCADE,
                to="egrid.plantutility",
                to_field="utlsrvid",
            ),
        ),
    ]
