# Generated by Django 5.2 on 2025-04-25 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0030_remove_plant_namepcap_plantadjustedvalues_namepcap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="subrgn",
            field=models.ForeignKey(
                db_column="subrgn",
                on_delete=django.db.models.deletion.CASCADE,
                to="egrid.subregion",
            ),
        ),
    ]
