# Generated by Django 5.1.5 on 2025-04-02 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0030_alter_baannualcombustion_bacode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baannualcombustion',
            name='bacode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egrid.balancingauthority'),
        ),
    ]
