# Generated by Django 5.2 on 2025-04-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0031_plantutility_delete_county_remove_plant_pstatabb_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="oprcode",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
