# Generated by Django 5.2 on 2025-04-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0031_alter_plant_subrgn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nercregion",
            name="nrnamepcap",
        ),
    ]
