# Generated by Django 5.1.5 on 2025-04-02 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0031_alter_baannualcombustion_bacode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baannualcombustion',
            name='bacode',
            field=models.ForeignKey(db_column='bacode', on_delete=django.db.models.deletion.CASCADE, to='egrid.balancingauthority'),
        ),
    ]
