# Generated by Django 5.2 on 2025-04-25 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0032_remove_nercregion_nrnamepcap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="nerc",
            field=models.ForeignKey(
                db_column="nerc",
                on_delete=django.db.models.deletion.CASCADE,
                to="egrid.nercregion",
                to_field="nerc",
            ),
        ),
    ]
