# Generated by Django 5.1.5 on 2025-04-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0032_alter_baannualcombustion_bacode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequnt', models.IntegerField(blank=True, null=True)),
                ('orispl', models.IntegerField(unique=True)),
                ('pstatabb', models.CharField(blank=True, max_length=1000, null=True)),
                ('fipsst', models.CharField(blank=True, max_length=1000, null=True)),
                ('pname', models.CharField(blank=True, max_length=1000, null=True)),
                ('oprcode', models.IntegerField(blank=True, null=True)),
                ('utlsrvid', models.IntegerField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=1000, null=True)),
                ('bacode', models.CharField(blank=True, max_length=1000, null=True)),
                ('nerc', models.CharField(blank=True, max_length=1000, null=True)),
                ('fipscnty', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('numunt', models.IntegerField(blank=True, null=True)),
                ('numgen', models.IntegerField(blank=True, null=True)),
                ('plprmfl', models.CharField(blank=True, max_length=1000, null=True)),
                ('plfuelct', models.CharField(blank=True, max_length=1000, null=True)),
                ('coalflag', models.CharField(blank=True, max_length=1000, null=True)),
                ('subrgn', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'plant_temp',
            },
        ),
    ]
