# Generated by Django 5.1.5 on 2025-04-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0033_planttemp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantTemp',
        ),
    ]
