# Generated by Django 5.2 on 2025-04-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0033_alter_plant_nerc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balancingauthority",
            name="banamepcap",
        ),
    ]
