# Generated by Django 5.1.5 on 2025-04-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0034_delete_planttemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='sequnt',
            new_name='seqplt',
        ),
    ]
