# Generated by Django 5.2 on 2025-04-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0034_remove_balancingauthority_banamepcap"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantdistributionsys",
            name="id",
        ),
        migrations.RemoveField(
            model_name="plantdistributionsys",
            name="orispl",
        ),
        migrations.AddField(
            model_name="plantdistributionsys",
            name="opr_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="plantdistributionsys",
            name="oprcode",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="plantdistributionsys",
            name="oprname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
