# Generated by Django 5.2 on 2025-04-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0035_remove_plantdistributionsys_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantdistributionsys",
            name="opr_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
