# Generated by Django 5.1.5 on 2025-04-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0035_rename_sequnt_plant_seqplt'),
    ]

    operations = [
        migrations.AddField(
            model_name='baannualcombustion',
            name='bangennb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bafueltypeemissionrate',
            name='bafsc2ert',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bafueltypegeneration',
            name='bagenaco',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bafueltypegeneration',
            name='bagenato',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baresourcemix',
            name='bacopr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baresourcemix',
            name='batopr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baannualcombustion',
            name='bahgan',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baemissionrate',
            name='bahgcrt',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baemissionrate',
            name='bahgra',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baemissionrate',
            name='bahgrta',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bafueltypeemissionrate',
            name='bachgr',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bafueltypeemissionrate',
            name='bachgrt',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bafueltypeemissionrate',
            name='bafshgr',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bafueltypeemissionrate',
            name='bafshgrt',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='generator',
            constraint=models.UniqueConstraint(fields=('genid', 'orispl'), name='unique_genid_orispl'),
        ),
    ]
