# Generated by Django 5.2 on 2025-04-25 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0036_alter_plantdistributionsys_opr_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="opr_id",
            field=models.ForeignKey(
                db_column="opr_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="egrid.plantdistributionsys",
            ),
            preserve_default=False,
        ),
    ]
