# Generated by Django 5.1.5 on 2025-04-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0036_baannualcombustion_bangennb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genid', models.CharField(blank=True, null=True)),
                ('orispl', models.IntegerField()),
                ('numblr', models.IntegerField(blank=True, null=True)),
                ('genstat', models.CharField(blank=True, max_length=500, null=True)),
                ('prmvr', models.CharField(blank=True, max_length=500, null=True)),
                ('fuelg1', models.CharField(blank=True, max_length=500, null=True)),
                ('namepcap', models.FloatField(blank=True, null=True)),
                ('cfact', models.FloatField(blank=True, null=True)),
                ('genntan', models.FloatField(blank=True, null=True)),
                ('genntoz', models.FloatField(blank=True, null=True)),
                ('genersrc', models.CharField(blank=True, max_length=500, null=True)),
                ('genyronl', models.IntegerField(blank=True, null=True)),
                ('genyrret', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'Generation',
                'constraints': [models.UniqueConstraint(fields=('genid', 'orispl', 'year'), name='unique_genid_orispl_year')],
            },
        ),
    ]
