# Generated by Django 5.1.5 on 2025-04-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egrid', '0037_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
