# Generated by Django 5.2 on 2025-04-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0037_plant_opr_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plant",
            name="oprcode",
        ),
    ]
