# Generated by Django 5.2 on 2025-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0038_remove_plant_oprcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantUtility",
            fields=[
                ("utlsrvid", models.IntegerField(primary_key=True, serialize=False)),
                ("utlsrvname", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "plant_utility",
            },
        ),
        migrations.DeleteModel(
            name="Utility",
        ),
    ]
