# Generated by Django 5.2 on 2025-04-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0039_plantutility_delete_utility"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantutility",
            old_name="utlsrvname",
            new_name="utlsrvnm",
        ),
    ]
