# Generated by Django 5.2 on 2025-04-25 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0040_rename_utlsrvname_plantutility_utlsrvnm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="utlsrvid",
            field=models.ForeignKey(
                db_column="utlsrvid",
                on_delete=django.db.models.deletion.CASCADE,
                to="egrid.plantutility",
            ),
        ),
    ]
