# Generated by Django 5.2 on 2025-04-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0041_alter_plant_utlsrvid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="county",
            name="id",
        ),
        migrations.RemoveField(
            model_name="generator",
            name="seqgen",
        ),
        migrations.AddField(
            model_name="county",
            name="cnty_id",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="county",
            name="fipscnty",
            field=models.CharField(max_length=5),
        ),
    ]
