# Generated by Django 5.2 on 2025-04-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0042_remove_county_id_remove_generator_seqgen_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="sequnt",
        ),
    ]
