# Generated by Django 5.2 on 2025-04-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0043_remove_unit_sequnt"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="County",
            new_name="PlantCounty",
        ),
    ]
