# Generated by Django 5.2 on 2025-04-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0044_rename_county_plantcounty"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="plantcounty",
            table="plant_county",
        ),
    ]
