# Generated by Django 5.2 on 2025-04-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0045_alter_plantcounty_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantcounty",
            name="cntyname",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="plantcounty",
            name="fipscnty",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
