# Generated by Django 5.2 on 2025-04-25 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0046_alter_plantcounty_cntyname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plant",
            name="fipscnty",
        ),
        migrations.AddField(
            model_name="plant",
            name="cnty_id",
            field=models.ForeignKey(
                db_column="cnty_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="egrid.plantcounty",
            ),
            preserve_default=False,
        ),
    ]
