# Generated by Django 5.2 on 2025-04-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egrid", "0047_remove_plant_fipscnty_plant_cnty_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitunadjustedvalues",
            name="so2ctldv",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
